# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: content/browser/cookie_store/cookie_change_subscriptions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'content/browser/cookie_store/cookie_change_subscriptions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>content/browser/cookie_store/cookie_change_subscriptions.proto\x12\rcontent.proto\"n\n\x1d\x43ookieChangeSubscriptionProto\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x32\n\nmatch_type\x18\x03 \x01(\x0e\x32\x1e.content.proto.CookieMatchType\"e\n\x1e\x43ookieChangeSubscriptionsProto\x12\x43\n\rsubscriptions\x18\x01 \x03(\x0b\x32,.content.proto.CookieChangeSubscriptionProto*.\n\x0f\x43ookieMatchType\x12\n\n\x06\x45QUALS\x10\x00\x12\x0f\n\x0bSTARTS_WITH\x10\x01\x42\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'content.browser.cookie_store.cookie_change_subscriptions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_COOKIEMATCHTYPE']._serialized_start=296
  _globals['_COOKIEMATCHTYPE']._serialized_end=342
  _globals['_COOKIECHANGESUBSCRIPTIONPROTO']._serialized_start=81
  _globals['_COOKIECHANGESUBSCRIPTIONPROTO']._serialized_end=191
  _globals['_COOKIECHANGESUBSCRIPTIONSPROTO']._serialized_start=193
  _globals['_COOKIECHANGESUBSCRIPTIONSPROTO']._serialized_end=294
# @@protoc_insertion_point(module_scope)
