# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/download/database/proto/download_source.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/download/database/proto/download_source.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8components/download/database/proto/download_source.proto\x12\x0b\x64ownload_pb*\xff\x01\n\x0e\x44ownloadSource\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nNAVIGATION\x10\x01\x12\x11\n\rDRAG_AND_DROP\x10\x02\x12\x11\n\rFROM_RENDERER\x10\x03\x12\x11\n\rEXTENSION_API\x10\x04\x12\x17\n\x13\x45XTENSION_INSTALLER\x10\x05\x12\x10\n\x0cINTERNAL_API\x10\x06\x12\x14\n\x10WEB_CONTENTS_API\x10\x07\x12\x10\n\x0cOFFLINE_PAGE\x10\x08\x12\x10\n\x0c\x43ONTEXT_MENU\x10\t\x12\t\n\x05RETRY\x10\n\x12\x15\n\x11RETRY_FROM_BUBBLE\x10\x0b\x12\x10\n\x0cTOOLBAR_MENU\x10\x0c\x42\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.download.database.proto.download_source_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_DOWNLOADSOURCE']._serialized_start=74
  _globals['_DOWNLOADSOURCE']._serialized_end=329
# @@protoc_insertion_point(module_scope)
