# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/app_list_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/app_list_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1components/sync/protocol/app_list_specifics.proto\x12\x07sync_pb\"\xb3\x05\n\x10\x41ppListSpecifics\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12<\n\titem_type\x18\x02 \x01(\x0e\x32).sync_pb.AppListSpecifics.AppListItemType\x12\x11\n\titem_name\x18\x03 \x01(\t\x12\x11\n\tparent_id\x18\x04 \x01(\t\x12!\n\x15OBSOLETE_page_ordinal\x18\x05 \x01(\tB\x02\x18\x01\x12\x14\n\x0citem_ordinal\x18\x06 \x01(\t\x12\x18\n\x10item_pin_ordinal\x18\x07 \x01(\t\x12\x37\n\nitem_color\x18\x08 \x01(\x0b\x32#.sync_pb.AppListSpecifics.IconColor\x12\x1a\n\x12promise_package_id\x18\n \x01(\t\x1aX\n\tIconColor\x12>\n\x10\x62\x61\x63kground_color\x18\x01 \x01(\x0e\x32$.sync_pb.AppListSpecifics.ColorGroup\x12\x0b\n\x03hue\x18\x02 \x01(\x05\"y\n\x0f\x41ppListItemType\x12\x0c\n\x08TYPE_APP\x10\x01\x12\x1b\n\x17TYPE_REMOVE_DEFAULT_APP\x10\x02\x12\x0f\n\x0bTYPE_FOLDER\x10\x03\x12\x15\n\x11TYPE_OBSOLETE_URL\x10\x04\x12\x13\n\x0fTYPE_PAGE_BREAK\x10\x05\"\xa6\x01\n\nColorGroup\x12\x0f\n\x0b\x43OLOR_EMPTY\x10\x00\x12\x0f\n\x0b\x43OLOR_WHITE\x10\x01\x12\r\n\tCOLOR_RED\x10\x02\x12\x10\n\x0c\x43OLOR_ORANGE\x10\x03\x12\x10\n\x0c\x43OLOR_YELLOW\x10\x04\x12\x0f\n\x0b\x43OLOR_GREEN\x10\x05\x12\x0e\n\nCOLOR_BLUE\x10\x06\x12\x11\n\rCOLOR_MAGENTA\x10\x07\x12\x0f\n\x0b\x43OLOR_BLACK\x10\x08J\x04\x08\t\x10\nB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.app_list_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_APPLISTSPECIFICS'].fields_by_name['OBSOLETE_page_ordinal']._loaded_options = None
  _globals['_APPLISTSPECIFICS'].fields_by_name['OBSOLETE_page_ordinal']._serialized_options = b'\030\001'
  _globals['_APPLISTSPECIFICS']._serialized_start=63
  _globals['_APPLISTSPECIFICS']._serialized_end=754
  _globals['_APPLISTSPECIFICS_ICONCOLOR']._serialized_start=368
  _globals['_APPLISTSPECIFICS_ICONCOLOR']._serialized_end=456
  _globals['_APPLISTSPECIFICS_APPLISTITEMTYPE']._serialized_start=458
  _globals['_APPLISTSPECIFICS_APPLISTITEMTYPE']._serialized_end=579
  _globals['_APPLISTSPECIFICS_COLORGROUP']._serialized_start=582
  _globals['_APPLISTSPECIFICS_COLORGROUP']._serialized_end=748
# @@protoc_insertion_point(module_scope)
