# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/autofill_valuable_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/autofill_valuable_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:components/sync/protocol/autofill_valuable_specifics.proto\x12\x07sync_pb\"&\n\x03\x41ny\x12\x10\n\x08type_url\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x87\x01\n\x0bLoyaltyCard\x12\x15\n\rmerchant_name\x18\x01 \x01(\t\x12\x14\n\x0cprogram_name\x18\x02 \x01(\t\x12\x14\n\x0cprogram_logo\x18\x03 \x01(\t\x12\x1b\n\x13loyalty_card_number\x18\x04 \x01(\t\x12\x18\n\x10merchant_domains\x18\x05 \x03(\t\"\xef\x01\n\x13VehicleRegistration\x12\x14\n\x0cvehicle_make\x18\x01 \x01(\t\x12\x15\n\rvehicle_model\x18\x02 \x01(\t\x12\x14\n\x0cvehicle_year\x18\x03 \x01(\t\x12%\n\x1dvehicle_identification_number\x18\x04 \x01(\t\x12\x1d\n\x15vehicle_license_plate\x18\x05 \x01(\t\x12\x1c\n\x14license_plate_region\x18\x06 \x01(\t\x12\x1d\n\x15license_plate_country\x18\x07 \x01(\t\x12\x12\n\nowner_name\x18\x08 \x01(\t\"\x88\x02\n\x11\x46lightReservation\x12\x15\n\rflight_number\x18\x01 \x01(\t\x12\x1c\n\x14\x66light_ticket_number\x18\x02 \x01(\t\x12 \n\x18\x66light_confirmation_code\x18\x03 \x01(\t\x12\x16\n\x0epassenger_name\x18\x04 \x01(\t\x12\x19\n\x11\x64\x65parture_airport\x18\x05 \x01(\t\x12\x17\n\x0f\x61rrival_airport\x18\x06 \x01(\t\x12(\n departure_date_unix_epoch_micros\x18\x07 \x01(\x03\x12&\n\x1e\x61rrival_date_unix_epoch_micros\x18\x08 \x01(\x03\"\xaf\x02\n\x19\x41utofillValuableSpecifics\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0bis_editable\x18\x06 \x01(\x08\x12,\n\x0cloyalty_card\x18\x02 \x01(\x0b\x32\x14.sync_pb.LoyaltyCardH\x00\x12<\n\x14vehicle_registration\x18\x03 \x01(\x0b\x32\x1c.sync_pb.VehicleRegistrationH\x00\x12\x38\n\x12\x66light_reservation\x18\x05 \x01(\x0b\x32\x1a.sync_pb.FlightReservationH\x00\x12:\n$serialized_chrome_valuables_metadata\x18\x04 \x01(\x0b\x32\x0c.sync_pb.AnyB\x0f\n\rvaluable_dataB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.autofill_valuable_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_ANY']._serialized_start=71
  _globals['_ANY']._serialized_end=109
  _globals['_LOYALTYCARD']._serialized_start=112
  _globals['_LOYALTYCARD']._serialized_end=247
  _globals['_VEHICLEREGISTRATION']._serialized_start=250
  _globals['_VEHICLEREGISTRATION']._serialized_end=489
  _globals['_FLIGHTRESERVATION']._serialized_start=492
  _globals['_FLIGHTRESERVATION']._serialized_end=756
  _globals['_AUTOFILLVALUABLESPECIFICS']._serialized_start=759
  _globals['_AUTOFILLVALUABLESPECIFICS']._serialized_end=1062
# @@protoc_insertion_point(module_scope)
