# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/autofill_wallet_credential_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/autofill_wallet_credential_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCcomponents/sync/protocol/autofill_wallet_credential_specifics.proto\x12\x07sync_pb\"t\n!AutofillWalletCredentialSpecifics\x12\x15\n\rinstrument_id\x18\x01 \x01(\t\x12\x0b\n\x03\x63vc\x18\x02 \x01(\t\x12+\n#last_updated_time_unix_epoch_millis\x18\x03 \x01(\x03\x42+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.autofill_wallet_credential_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_AUTOFILLWALLETCREDENTIALSPECIFICS']._serialized_start=80
  _globals['_AUTOFILLWALLETCREDENTIALSPECIFICS']._serialized_end=196
# @@protoc_insertion_point(module_scope)
