# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/autofill_wallet_usage_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/autofill_wallet_usage_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>components/sync/protocol/autofill_wallet_usage_specifics.proto\x12\x07sync_pb\"\xa2\x02\n\x1c\x41utofillWalletUsageSpecifics\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12]\n\x17virtual_card_usage_data\x18\x02 \x01(\x0b\x32:.sync_pb.AutofillWalletUsageSpecifics.VirtualCardUsageDataH\x00\x1a\x81\x01\n\x14VirtualCardUsageData\x12\x15\n\rinstrument_id\x18\x01 \x01(\x03\x12\x1e\n\x16virtual_card_last_four\x18\x02 \x01(\t\x12\x14\n\x0cmerchant_url\x18\x03 \x01(\t\x12\x1c\n\x14merchant_app_package\x18\x04 \x01(\tB\x11\n\x0fusage_data_typeB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.autofill_wallet_usage_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_AUTOFILLWALLETUSAGESPECIFICS']._serialized_start=76
  _globals['_AUTOFILLWALLETUSAGESPECIFICS']._serialized_end=366
  _globals['_AUTOFILLWALLETUSAGESPECIFICS_VIRTUALCARDUSAGEDATA']._serialized_start=218
  _globals['_AUTOFILLWALLETUSAGESPECIFICS_VIRTUALCARDUSAGEDATA']._serialized_end=347
# @@protoc_insertion_point(module_scope)
