# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/autofill_offer_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/autofill_offer_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7components/sync/protocol/autofill_offer_specifics.proto\x12\x07sync_pb\"\xc3\x07\n\x16\x41utofillOfferSpecifics\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x19\n\x11offer_details_url\x18\x02 \x01(\t\x12\x17\n\x0fmerchant_domain\x18\x03 \x03(\t\x12\x1c\n\x14merchant_app_package\x18\x04 \x03(\t\x12\x19\n\x11offer_expiry_date\x18\x05 \x01(\x03\x12U\n\x16\x63\x61rd_linked_offer_data\x18\x06 \x01(\x0b\x32\x33.sync_pb.AutofillOfferSpecifics.CardLinkedOfferDataH\x00\x12S\n\x15promo_code_offer_data\x18\t \x01(\x0b\x32\x32.sync_pb.AutofillOfferSpecifics.PromoCodeOfferDataH\x00\x12G\n\x0f\x64isplay_strings\x18\n \x01(\x0b\x32..sync_pb.AutofillOfferSpecifics.DisplayStrings\x12M\n\x11percentage_reward\x18\x07 \x01(\x0b\x32\x30.sync_pb.AutofillOfferSpecifics.PercentageRewardH\x01\x12P\n\x13\x66ixed_amount_reward\x18\x08 \x01(\x0b\x32\x31.sync_pb.AutofillOfferSpecifics.FixedAmountRewardH\x01\x1a\x38\n\x13\x43\x61rdLinkedOfferData\x12\x15\n\rinstrument_id\x18\x03 \x03(\x03J\x04\x08\x01\x10\x02J\x04\x08\x02\x10\x03\x1a(\n\x12PromoCodeOfferData\x12\x12\n\npromo_code\x18\x01 \x01(\t\x1a\xbd\x01\n\x0e\x44isplayStrings\x12\x17\n\x0fvalue_prop_text\x18\x01 \x01(\t\x12\x1f\n\x17see_details_text_mobile\x18\x02 \x01(\t\x12 \n\x18see_details_text_desktop\x18\x03 \x01(\t\x12&\n\x1eusage_instructions_text_mobile\x18\x04 \x01(\t\x12\'\n\x1fusage_instructions_text_desktop\x18\x05 \x01(\t\x1a&\n\x10PercentageReward\x12\x12\n\npercentage\x18\x01 \x01(\t\x1a#\n\x11\x46ixedAmountReward\x12\x0e\n\x06\x61mount\x18\x01 \x01(\tB\x1a\n\x18type_specific_offer_dataB\r\n\x0breward_typeB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.autofill_offer_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_AUTOFILLOFFERSPECIFICS']._serialized_start=69
  _globals['_AUTOFILLOFFERSPECIFICS']._serialized_end=1032
  _globals['_AUTOFILLOFFERSPECIFICS_CARDLINKEDOFFERDATA']._serialized_start=622
  _globals['_AUTOFILLOFFERSPECIFICS_CARDLINKEDOFFERDATA']._serialized_end=678
  _globals['_AUTOFILLOFFERSPECIFICS_PROMOCODEOFFERDATA']._serialized_start=680
  _globals['_AUTOFILLOFFERSPECIFICS_PROMOCODEOFFERDATA']._serialized_end=720
  _globals['_AUTOFILLOFFERSPECIFICS_DISPLAYSTRINGS']._serialized_start=723
  _globals['_AUTOFILLOFFERSPECIFICS_DISPLAYSTRINGS']._serialized_end=912
  _globals['_AUTOFILLOFFERSPECIFICS_PERCENTAGEREWARD']._serialized_start=914
  _globals['_AUTOFILLOFFERSPECIFICS_PERCENTAGEREWARD']._serialized_end=952
  _globals['_AUTOFILLOFFERSPECIFICS_FIXEDAMOUNTREWARD']._serialized_start=954
  _globals['_AUTOFILLOFFERSPECIFICS_FIXEDAMOUNTREWARD']._serialized_end=989
# @@protoc_insertion_point(module_scope)
