# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/bookmark_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/bookmark_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import unique_position_pb2 as components_dot_sync_dot_protocol_dot_unique__position__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1components/sync/protocol/bookmark_specifics.proto\x12\x07sync_pb\x1a.components/sync/protocol/unique_position.proto\"&\n\x08MetaInfo\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xa6\x03\n\x11\x42ookmarkSpecifics\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0f\n\x07\x66\x61vicon\x18\x02 \x01(\x0c\x12\"\n\x1alegacy_canonicalized_title\x18\x03 \x01(\t\x12\x18\n\x10\x63reation_time_us\x18\x04 \x01(\x03\x12\x10\n\x08icon_url\x18\x05 \x01(\t\x12$\n\tmeta_info\x18\x06 \x03(\x0b\x32\x11.sync_pb.MetaInfo\x12\x0c\n\x04guid\x18\n \x01(\t\x12\x12\n\nfull_title\x18\x0b \x01(\t\x12\x13\n\x0bparent_guid\x18\x0e \x01(\t\x12-\n\x04type\x18\x0f \x01(\x0e\x32\x1f.sync_pb.BookmarkSpecifics.Type\x12\x30\n\x0funique_position\x18\x10 \x01(\x0b\x32\x17.sync_pb.UniquePosition\x12\x19\n\x11last_used_time_us\x18\x11 \x01(\x03\",\n\x04Type\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x07\n\x03URL\x10\x01\x12\n\n\x06\x46OLDER\x10\x02J\x04\x08\x07\x10\x08J\x04\x08\x08\x10\tJ\x04\x08\t\x10\nJ\x04\x08\x0c\x10\rJ\x04\x08\r\x10\x0e\x42+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.bookmark_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_METAINFO']._serialized_start=110
  _globals['_METAINFO']._serialized_end=148
  _globals['_BOOKMARKSPECIFICS']._serialized_start=151
  _globals['_BOOKMARKSPECIFICS']._serialized_end=573
  _globals['_BOOKMARKSPECIFICS_TYPE']._serialized_start=499
  _globals['_BOOKMARKSPECIFICS_TYPE']._serialized_end=543
# @@protoc_insertion_point(module_scope)
