# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/bookmark_model_metadata.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/bookmark_model_metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import data_type_state_pb2 as components_dot_sync_dot_protocol_dot_data__type__state__pb2
from components.sync.protocol import entity_metadata_pb2 as components_dot_sync_dot_protocol_dot_entity__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6components/sync/protocol/bookmark_model_metadata.proto\x12\x07sync_pb\x1a.components/sync/protocol/data_type_state.proto\x1a.components/sync/protocol/entity_metadata.proto\"I\n\x10\x42ookmarkMetadata\x12\n\n\x02id\x18\x01 \x01(\x03\x12)\n\x08metadata\x18\x02 \x01(\x0b\x32\x17.sync_pb.EntityMetadata\"\xee\x02\n\x15\x42ookmarkModelMetadata\x12/\n\x0f\x64\x61ta_type_state\x18\x01 \x01(\x0b\x32\x16.sync_pb.DataTypeState\x12\x35\n\x12\x62ookmarks_metadata\x18\x02 \x03(\x0b\x32\x19.sync_pb.BookmarkMetadata\x12-\n%bookmarks_hierarchy_fields_reuploaded\x18\x06 \x01(\x08\x12\x31\n)num_ignored_updates_due_to_missing_parent\x18\x07 \x01(\x03\x12?\n7max_version_among_ignored_updates_due_to_missing_parent\x18\x08 \x01(\x03\x12\x38\n0last_initial_merge_remote_updates_exceeded_limit\x18\t \x01(\x08J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05J\x04\x08\x05\x10\x06\x42+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.bookmark_model_metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_BOOKMARKMETADATA']._serialized_start=163
  _globals['_BOOKMARKMETADATA']._serialized_end=236
  _globals['_BOOKMARKMODELMETADATA']._serialized_start=239
  _globals['_BOOKMARKMODELMETADATA']._serialized_end=605
# @@protoc_insertion_point(module_scope)
