# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/client_commands.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/client_commands.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.components/sync/protocol/client_commands.proto\x12\x07sync_pb\"9\n\x10\x43ustomNudgeDelay\x12\x13\n\x0b\x64\x61tatype_id\x18\x01 \x01(\x05\x12\x10\n\x08\x64\x65lay_ms\x18\x02 \x01(\x05\"\xd5\x03\n\rClientCommand\x12\x1e\n\x16set_sync_poll_interval\x18\x01 \x01(\x05\x12\'\n\x1bset_sync_long_poll_interval\x18\x02 \x01(\x05\x42\x02\x18\x01\x12\x1d\n\x15max_commit_batch_size\x18\x03 \x01(\x05\x12\x1e\n\x16throttle_delay_seconds\x18\x05 \x01(\x05\x12\x30\n$client_invalidation_hint_buffer_size\x18\x06 \x01(\x05\x42\x02\x18\x01\x12\x36\n\x13\x63ustom_nudge_delays\x18\x08 \x03(\x0b\x32\x19.sync_pb.CustomNudgeDelay\x12\"\n\x1a\x65xtension_types_max_tokens\x18\t \x01(\x05\x12/\n\'extension_types_refill_interval_seconds\x18\n \x01(\x05\x12:\n2extension_types_depleted_quota_nudge_delay_seconds\x18\x0b \x01(\x05J\x04\x08\x04\x10\x05J\x04\x08\x07\x10\x08R\x1dsessions_commit_delay_secondsR\x16gu_retry_delay_secondsB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.client_commands_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_CLIENTCOMMAND'].fields_by_name['set_sync_long_poll_interval']._loaded_options = None
  _globals['_CLIENTCOMMAND'].fields_by_name['set_sync_long_poll_interval']._serialized_options = b'\030\001'
  _globals['_CLIENTCOMMAND'].fields_by_name['client_invalidation_hint_buffer_size']._loaded_options = None
  _globals['_CLIENTCOMMAND'].fields_by_name['client_invalidation_hint_buffer_size']._serialized_options = b'\030\001'
  _globals['_CUSTOMNUDGEDELAY']._serialized_start=59
  _globals['_CUSTOMNUDGEDELAY']._serialized_end=116
  _globals['_CLIENTCOMMAND']._serialized_start=119
  _globals['_CLIENTCOMMAND']._serialized_end=588
# @@protoc_insertion_point(module_scope)
