# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/client_debug_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/client_debug_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import get_updates_caller_info_pb2 as components_dot_sync_dot_protocol_dot_get__updates__caller__info__pb2
from components.sync.protocol import sync_enums_pb2 as components_dot_sync_dot_protocol_dot_sync__enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0components/sync/protocol/client_debug_info.proto\x12\x07sync_pb\x1a\x36\x63omponents/sync/protocol/get_updates_caller_info.proto\x1a)components/sync/protocol/sync_enums.proto\"8\n\x08TypeHint\x12\x14\n\x0c\x64\x61ta_type_id\x18\x01 \x01(\x05\x12\x16\n\x0ehas_valid_hint\x18\x02 \x01(\x08\"\xce\x03\n\x1bSyncCycleCompletedEventInfo\x12$\n\x18num_encryption_conflicts\x18\x04 \x01(\x05\x42\x02\x18\x01\x12#\n\x17num_hierarchy_conflicts\x18\x05 \x01(\x05\x42\x02\x18\x01\x12\x1c\n\x14num_simple_conflicts\x18\x06 \x01(\x05\x12\x1c\n\x14num_server_conflicts\x18\x07 \x01(\x05\x12\x1e\n\x16num_updates_downloaded\x18\x08 \x01(\x05\x12,\n num_reflected_updates_downloaded\x18\t \x01(\x05\x42\x02\x18\x01\x12\x32\n\x0b\x63\x61ller_info\x18\n \x01(\x0b\x32\x1d.sync_pb.GetUpdatesCallerInfo\x12?\n\x12get_updates_origin\x18\x0c \x01(\x0e\x32#.sync_pb.SyncEnums.GetUpdatesOriginJ\x04\x08\x01\x10\x02J\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\x0b\x10\x0cR\x0csyncer_stuckR\x16num_blocking_conflictsR\x1anum_non_blocking_conflictsR\x0bsource_info\"\x88\x02\n\x0e\x44\x65\x62ugEventInfo\x12\x43\n\x0fsingleton_event\x18\x01 \x01(\x0e\x32*.sync_pb.SyncEnums.SingletonDebugEventType\x12M\n\x1fsync_cycle_completed_event_info\x18\x02 \x01(\x0b\x32$.sync_pb.SyncCycleCompletedEventInfo\x12\x18\n\x10nudging_datatype\x18\x03 \x01(\x05\x12&\n\x1e\x64\x61tatypes_notified_from_server\x18\x04 \x03(\x05J\x04\x08\x05\x10\x06R\x1a\x64\x61tatype_association_stats\"\x91\x01\n\tDebugInfo\x12\'\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x17.sync_pb.DebugEventInfo\x12\x1b\n\x13\x63ryptographer_ready\x18\x02 \x01(\x08\x12&\n\x1e\x63ryptographer_has_pending_keys\x18\x03 \x01(\x08\x12\x16\n\x0e\x65vents_dropped\x18\x04 \x01(\x08\x42+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.client_debug_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_SYNCCYCLECOMPLETEDEVENTINFO'].fields_by_name['num_encryption_conflicts']._loaded_options = None
  _globals['_SYNCCYCLECOMPLETEDEVENTINFO'].fields_by_name['num_encryption_conflicts']._serialized_options = b'\030\001'
  _globals['_SYNCCYCLECOMPLETEDEVENTINFO'].fields_by_name['num_hierarchy_conflicts']._loaded_options = None
  _globals['_SYNCCYCLECOMPLETEDEVENTINFO'].fields_by_name['num_hierarchy_conflicts']._serialized_options = b'\030\001'
  _globals['_SYNCCYCLECOMPLETEDEVENTINFO'].fields_by_name['num_reflected_updates_downloaded']._loaded_options = None
  _globals['_SYNCCYCLECOMPLETEDEVENTINFO'].fields_by_name['num_reflected_updates_downloaded']._serialized_options = b'\030\001'
  _globals['_TYPEHINT']._serialized_start=160
  _globals['_TYPEHINT']._serialized_end=216
  _globals['_SYNCCYCLECOMPLETEDEVENTINFO']._serialized_start=219
  _globals['_SYNCCYCLECOMPLETEDEVENTINFO']._serialized_end=681
  _globals['_DEBUGEVENTINFO']._serialized_start=684
  _globals['_DEBUGEVENTINFO']._serialized_end=948
  _globals['_DEBUGINFO']._serialized_start=951
  _globals['_DEBUGINFO']._serialized_end=1096
# @@protoc_insertion_point(module_scope)
