# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/cookie_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/cookie_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/components/sync/protocol/cookie_specifics.proto\x12\x07sync_pb\"\x95\x08\n\x0f\x43ookieSpecifics\x12\x12\n\nunique_key\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x0e\n\x06\x64omain\x18\x04 \x01(\t\x12\x0c\n\x04path\x18\x05 \x01(\t\x12*\n\"creation_time_windows_epoch_micros\x18\x06 \x01(\x03\x12(\n expiry_time_windows_epoch_micros\x18\x07 \x01(\x03\x12-\n%last_access_time_windows_epoch_micros\x18\x08 \x01(\x03\x12-\n%last_update_time_windows_epoch_micros\x18\t \x01(\x03\x12\x0e\n\x06secure\x18\n \x01(\x08\x12\x10\n\x08httponly\x18\x0b \x01(\x08\x12\x42\n\x11site_restrictions\x18\x0c \x01(\x0e\x32\'.sync_pb.CookieSpecifics.CookieSameSite\x12\x39\n\x08priority\x18\r \x01(\x0e\x32\'.sync_pb.CookieSpecifics.CookiePriority\x12\x42\n\rsource_scheme\x18\x0e \x01(\x0e\x32+.sync_pb.CookieSpecifics.CookieSourceScheme\x12L\n\rpartition_key\x18\x0f \x01(\x0b\x32\x35.sync_pb.CookieSpecifics.SerializedCookiePartitionKey\x12\x13\n\x0bsource_port\x18\x10 \x01(\x05\x12>\n\x0bsource_type\x18\x11 \x01(\x0e\x32).sync_pb.CookieSpecifics.CookieSourceType\x1aW\n\x1cSerializedCookiePartitionKey\x12\x16\n\x0etop_level_site\x18\x01 \x01(\t\x12\x1f\n\x17has_cross_site_ancestor\x18\x02 \x01(\x08\"T\n\x0e\x43ookieSameSite\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x12\n\x0eNO_RESTRICTION\x10\x01\x12\x0c\n\x08LAX_MODE\x10\x02\x12\x0f\n\x0bSTRICT_MODE\x10\x03\"I\n\x0e\x43ookiePriority\x12\x18\n\x14UNSPECIFIED_PRIORITY\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\n\n\x06MEDIUM\x10\x02\x12\x08\n\x04HIGH\x10\x03\";\n\x12\x43ookieSourceScheme\x12\t\n\x05UNSET\x10\x00\x12\x0e\n\nNON_SECURE\x10\x01\x12\n\n\x06SECURE\x10\x02\"@\n\x10\x43ookieSourceType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04HTTP\x10\x01\x12\n\n\x06SCRIPT\x10\x02\x12\t\n\x05OTHER\x10\x03\x42+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.cookie_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_COOKIESPECIFICS']._serialized_start=61
  _globals['_COOKIESPECIFICS']._serialized_end=1106
  _globals['_COOKIESPECIFICS_SERIALIZEDCOOKIEPARTITIONKEY']._serialized_start=731
  _globals['_COOKIESPECIFICS_SERIALIZEDCOOKIEPARTITIONKEY']._serialized_end=818
  _globals['_COOKIESPECIFICS_COOKIESAMESITE']._serialized_start=820
  _globals['_COOKIESPECIFICS_COOKIESAMESITE']._serialized_end=904
  _globals['_COOKIESPECIFICS_COOKIEPRIORITY']._serialized_start=906
  _globals['_COOKIESPECIFICS_COOKIEPRIORITY']._serialized_end=979
  _globals['_COOKIESPECIFICS_COOKIESOURCESCHEME']._serialized_start=981
  _globals['_COOKIESPECIFICS_COOKIESOURCESCHEME']._serialized_end=1040
  _globals['_COOKIESPECIFICS_COOKIESOURCETYPE']._serialized_start=1042
  _globals['_COOKIESPECIFICS_COOKIESOURCETYPE']._serialized_end=1106
# @@protoc_insertion_point(module_scope)
