# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/data_type_state.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/data_type_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import data_type_progress_marker_pb2 as components_dot_sync_dot_protocol_dot_data__type__progress__marker__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.components/sync/protocol/data_type_state.proto\x12\x07sync_pb\x1a\x38\x63omponents/sync/protocol/data_type_progress_marker.proto\"\xe5\x04\n\rDataTypeState\x12\x38\n\x0fprogress_marker\x18\x01 \x01(\x0b\x32\x1f.sync_pb.DataTypeProgressMarker\x12.\n\x0ctype_context\x18\x02 \x01(\x0b\x32\x18.sync_pb.DataTypeContext\x12\x1b\n\x13\x65ncryption_key_name\x18\x03 \x01(\t\x12\x43\n\x12initial_sync_state\x18\t \x01(\x0e\x32\'.sync_pb.DataTypeState.InitialSyncState\x12\x12\n\ncache_guid\x18\x05 \x01(\t\x12(\n authenticated_obfuscated_gaia_id\x18\x06 \x01(\t\x12:\n\rinvalidations\x18\x07 \x03(\x0b\x32#.sync_pb.DataTypeState.Invalidation\x12\x37\n/notes_enabled_before_initial_sync_for_passwords\x18\x08 \x01(\x08\x1a-\n\x0cInvalidation\x12\x0c\n\x04hint\x18\x01 \x01(\x0c\x12\x0f\n\x07version\x18\x02 \x01(\x03\"\x8c\x01\n\x10InitialSyncState\x12\"\n\x1eINITIAL_SYNC_STATE_UNSPECIFIED\x10\x00\x12\x1f\n\x1bINITIAL_SYNC_PARTIALLY_DONE\x10\x02\x12\x15\n\x11INITIAL_SYNC_DONE\x10\x03\x12\x1c\n\x18INITIAL_SYNC_UNNECESSARY\x10\x04J\x04\x08\x04\x10\x05R\x11initial_sync_doneB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.data_type_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_DATATYPESTATE']._serialized_start=118
  _globals['_DATATYPESTATE']._serialized_end=731
  _globals['_DATATYPESTATE_INVALIDATION']._serialized_start=518
  _globals['_DATATYPESTATE_INVALIDATION']._serialized_end=563
  _globals['_DATATYPESTATE_INITIALSYNCSTATE']._serialized_start=566
  _globals['_DATATYPESTATE_INITIALSYNCSTATE']._serialized_end=706
# @@protoc_insertion_point(module_scope)
