# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/data_type_progress_marker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/data_type_progress_marker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8components/sync/protocol/data_type_progress_marker.proto\x12\x07sync_pb\"\xef\x01\n\x16\x44\x61taTypeProgressMarker\x12\x14\n\x0c\x64\x61ta_type_id\x18\x01 \x01(\x05\x12\r\n\x05token\x18\x02 \x01(\x0c\x12\x37\n\x13get_update_triggers\x18\x05 \x01(\x0b\x32\x1a.sync_pb.GetUpdateTriggers\x12\x39\n\x0cgc_directive\x18\x06 \x01(\x0b\x32#.sync_pb.GarbageCollectionDirectiveJ\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05R\x1dtimestamp_token_for_migrationR\x11notification_hint\"I\n\x0f\x44\x61taTypeContext\x12\x14\n\x0c\x64\x61ta_type_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\x0c\x12\x0f\n\x07version\x18\x03 \x01(\x03\"\xc7\x03\n\x1aGarbageCollectionDirective\x12\x43\n\x04type\x18\x01 \x01(\x0e\x32(.sync_pb.GarbageCollectionDirective.Type:\x07UNKNOWNB\x02\x18\x01\x12\x19\n\x11version_watermark\x18\x02 \x01(\x03\x12\\\n\x10\x63ollaboration_gc\x18\x05 \x01(\x0b\x32\x42.sync_pb.GarbageCollectionDirective.CollaborationGarbageCollection\x1a\x42\n\x1e\x43ollaborationGarbageCollection\x12 \n\x18\x61\x63tive_collaboration_ids\x18\x01 \x03(\t\"o\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x15\n\x11VERSION_WATERMARK\x10\x01\x12 \n\x18\x44\x45PRECATED_AGE_WATERMARK\x10\x02\x1a\x02\x08\x01\x12!\n\x19\x44\x45PRECATED_MAX_ITEM_COUNT\x10\x03\x1a\x02\x08\x01J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05R\x15\x61ge_watermark_in_daysR\x13max_number_of_items\"\xa2\x02\n\x11GetUpdateTriggers\x12\x19\n\x11notification_hint\x18\x01 \x03(\t\x12\x1c\n\x14\x63lient_dropped_hints\x18\x02 \x01(\x08\x12!\n\x19invalidations_out_of_sync\x18\x03 \x01(\x08\x12!\n\x19local_modification_nudges\x18\x04 \x01(\x03\x12\x1f\n\x17\x64\x61tatype_refresh_nudges\x18\x05 \x01(\x03\x12\x1c\n\x14server_dropped_hints\x18\x06 \x01(\x08\x12 \n\x18initial_sync_in_progress\x18\x07 \x01(\x08\x12-\n%sync_for_resolve_conflict_in_progress\x18\x08 \x01(\x08\x42+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.data_type_progress_marker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_GARBAGECOLLECTIONDIRECTIVE_TYPE'].values_by_name["DEPRECATED_AGE_WATERMARK"]._loaded_options = None
  _globals['_GARBAGECOLLECTIONDIRECTIVE_TYPE'].values_by_name["DEPRECATED_AGE_WATERMARK"]._serialized_options = b'\010\001'
  _globals['_GARBAGECOLLECTIONDIRECTIVE_TYPE'].values_by_name["DEPRECATED_MAX_ITEM_COUNT"]._loaded_options = None
  _globals['_GARBAGECOLLECTIONDIRECTIVE_TYPE'].values_by_name["DEPRECATED_MAX_ITEM_COUNT"]._serialized_options = b'\010\001'
  _globals['_GARBAGECOLLECTIONDIRECTIVE'].fields_by_name['type']._loaded_options = None
  _globals['_GARBAGECOLLECTIONDIRECTIVE'].fields_by_name['type']._serialized_options = b'\030\001'
  _globals['_DATATYPEPROGRESSMARKER']._serialized_start=70
  _globals['_DATATYPEPROGRESSMARKER']._serialized_end=309
  _globals['_DATATYPECONTEXT']._serialized_start=311
  _globals['_DATATYPECONTEXT']._serialized_end=384
  _globals['_GARBAGECOLLECTIONDIRECTIVE']._serialized_start=387
  _globals['_GARBAGECOLLECTIONDIRECTIVE']._serialized_end=842
  _globals['_GARBAGECOLLECTIONDIRECTIVE_COLLABORATIONGARBAGECOLLECTION']._serialized_start=607
  _globals['_GARBAGECOLLECTIONDIRECTIVE_COLLABORATIONGARBAGECOLLECTION']._serialized_end=673
  _globals['_GARBAGECOLLECTIONDIRECTIVE_TYPE']._serialized_start=675
  _globals['_GARBAGECOLLECTIONDIRECTIVE_TYPE']._serialized_end=786
  _globals['_GETUPDATETRIGGERS']._serialized_start=845
  _globals['_GETUPDATETRIGGERS']._serialized_end=1135
# @@protoc_insertion_point(module_scope)
