# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/deletion_origin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/deletion_origin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.components/sync/protocol/deletion_origin.proto\x12\x07sync_pb\"\xe6\x01\n\x0e\x44\x65letionOrigin\x12\x18\n\x10\x63hromium_version\x18\x01 \x01(\t\x12-\n%google_play_services_apk_version_name\x18\x02 \x01(\t\x12\x16\n\x0e\x66ile_name_hash\x18\x03 \x01(\x07\x12\x18\n\x10\x66ile_line_number\x18\x04 \x01(\x05\x12$\n\x1c\x66ile_name_possibly_truncated\x18\x05 \x01(\t\x12\x33\n+unique_source_tag_no_pii_possibly_truncated\x18\x06 \x01(\tB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.deletion_origin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_DELETIONORIGIN']._serialized_start=60
  _globals['_DELETIONORIGIN']._serialized_end=290
# @@protoc_insertion_point(module_scope)
