# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/encryption.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/encryption.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)components/sync/protocol/encryption.proto\x12\x07sync_pb\"/\n\rEncryptedData\x12\x10\n\x08key_name\x18\x01 \x01(\t\x12\x0c\n\x04\x62lob\x18\x02 \x01(\tB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.encryption_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_ENCRYPTEDDATA']._serialized_start=54
  _globals['_ENCRYPTEDDATA']._serialized_end=101
# @@protoc_insertion_point(module_scope)
