# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/entity_metadata.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/entity_metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import deletion_origin_pb2 as components_dot_sync_dot_protocol_dot_deletion__origin__pb2
from components.sync.protocol import entity_specifics_pb2 as components_dot_sync_dot_protocol_dot_entity__specifics__pb2
from components.sync.protocol import unique_position_pb2 as components_dot_sync_dot_protocol_dot_unique__position__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.components/sync/protocol/entity_metadata.proto\x12\x07sync_pb\x1a.components/sync/protocol/deletion_origin.proto\x1a/components/sync/protocol/entity_specifics.proto\x1a.components/sync/protocol/unique_position.proto\"\xc7\x06\n\x0e\x45ntityMetadata\x12\x17\n\x0f\x63lient_tag_hash\x18\x01 \x01(\t\x12\x11\n\tserver_id\x18\x02 \x01(\t\x12\x12\n\nis_deleted\x18\x03 \x01(\x08\x12\x17\n\x0fsequence_number\x18\x04 \x01(\x03\x12\x1d\n\x15\x61\x63ked_sequence_number\x18\x05 \x01(\x03\x12\x1a\n\x0eserver_version\x18\x06 \x01(\x03:\x02-1\x12\x15\n\rcreation_time\x18\x07 \x01(\x03\x12\x19\n\x11modification_time\x18\x08 \x01(\x03\x12\x16\n\x0especifics_hash\x18\t \x01(\t\x12\x1b\n\x13\x62\x61se_specifics_hash\x18\n \x01(\t\x12\x30\n\x0funique_position\x18\x0b \x01(\x0b\x32\x17.sync_pb.UniquePosition\x12\x1d\n\x15\x62ookmark_favicon_hash\x18\x0c \x01(\x07\x12\x41\n\x1fpossibly_trimmed_base_specifics\x18\r \x01(\x0b\x32\x18.sync_pb.EntitySpecifics\x12\x1a\n\x12\x64\x65leted_by_version\x18\x0e \x01(\t\x12\x44\n\rcollaboration\x18\x0f \x01(\x0b\x32-.sync_pb.EntityMetadata.CollaborationMetadata\x12\x30\n\x0f\x64\x65letion_origin\x18\x10 \x01(\x0b\x32\x17.sync_pb.DeletionOrigin\x1a\x91\x02\n\x15\x43ollaborationMetadata\x12\x18\n\x10\x63ollaboration_id\x18\x01 \x01(\t\x12W\n\x14\x63reation_attribution\x18\x02 \x01(\x0b\x32\x39.sync_pb.EntityMetadata.CollaborationMetadata.Attribution\x12Z\n\x17last_update_attribution\x18\x03 \x01(\x0b\x32\x39.sync_pb.EntityMetadata.CollaborationMetadata.Attribution\x1a)\n\x0b\x41ttribution\x12\x1a\n\x12obfuscated_gaia_id\x18\x01 \x01(\tB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.entity_metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_ENTITYMETADATA']._serialized_start=205
  _globals['_ENTITYMETADATA']._serialized_end=1044
  _globals['_ENTITYMETADATA_COLLABORATIONMETADATA']._serialized_start=771
  _globals['_ENTITYMETADATA_COLLABORATIONMETADATA']._serialized_end=1044
  _globals['_ENTITYMETADATA_COLLABORATIONMETADATA_ATTRIBUTION']._serialized_start=1003
  _globals['_ENTITYMETADATA_COLLABORATIONMETADATA_ATTRIBUTION']._serialized_end=1044
# @@protoc_insertion_point(module_scope)
