# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/get_updates_caller_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/get_updates_caller_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6components/sync/protocol/get_updates_caller_info.proto\x12\x07sync_pb\"C\n\x14GetUpdatesCallerInfo\x12\x1d\n\x15notifications_enabled\x18\x02 \x01(\x08J\x04\x08\x01\x10\x02R\x06sourceB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.get_updates_caller_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_GETUPDATESCALLERINFO']._serialized_start=67
  _globals['_GETUPDATESCALLERINFO']._serialized_end=134
# @@protoc_insertion_point(module_scope)
