# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/history_status.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/history_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-components/sync/protocol/history_status.proto\x12\x07sync_pb\"\x16\n\x14HistoryStatusRequest\"Z\n\x15HistoryStatusResponse\x12\'\n\x19min_poll_interval_seconds\x18\x01 \x01(\x05:\x04\x33\x36\x30\x30\x12\x18\n\x10has_derived_data\x18\x02 \x01(\x08\x42+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.history_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_HISTORYSTATUSREQUEST']._serialized_start=58
  _globals['_HISTORYSTATUSREQUEST']._serialized_end=80
  _globals['_HISTORYSTATUSRESPONSE']._serialized_start=82
  _globals['_HISTORYSTATUSRESPONSE']._serialized_end=172
# @@protoc_insertion_point(module_scope)
