# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/history_delete_directive_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/history_delete_directive_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAcomponents/sync/protocol/history_delete_directive_specifics.proto\x12\x07sync_pb\"\xdb\x01\n\x1fHistoryDeleteDirectiveSpecifics\x12\x39\n\x13global_id_directive\x18\x01 \x01(\x0b\x32\x1a.sync_pb.GlobalIdDirectiveH\x00\x12;\n\x14time_range_directive\x18\x02 \x01(\x0b\x32\x1b.sync_pb.TimeRangeDirectiveH\x00\x12.\n\rurl_directive\x18\x03 \x01(\x0b\x32\x15.sync_pb.UrlDirectiveH\x00\x42\x10\n\x0e\x64irective_type\"V\n\x11GlobalIdDirective\x12\x11\n\tglobal_id\x18\x01 \x03(\x03\x12\x17\n\x0fstart_time_usec\x18\x02 \x01(\x03\x12\x15\n\rend_time_usec\x18\x03 \x01(\x03\"T\n\x12TimeRangeDirective\x12\x17\n\x0fstart_time_usec\x18\x01 \x01(\x03\x12\x15\n\rend_time_usec\x18\x02 \x01(\x03\x12\x0e\n\x06\x61pp_id\x18\x03 \x01(\t\"B\n\x0cUrlDirective\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x15\n\rend_time_usec\x18\x02 \x01(\x03\x12\x0e\n\x06\x61pp_id\x18\x03 \x01(\tB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.history_delete_directive_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_HISTORYDELETEDIRECTIVESPECIFICS']._serialized_start=79
  _globals['_HISTORYDELETEDIRECTIVESPECIFICS']._serialized_end=298
  _globals['_GLOBALIDDIRECTIVE']._serialized_start=300
  _globals['_GLOBALIDDIRECTIVE']._serialized_end=386
  _globals['_TIMERANGEDIRECTIVE']._serialized_start=388
  _globals['_TIMERANGEDIRECTIVE']._serialized_end=472
  _globals['_URLDIRECTIVE']._serialized_start=474
  _globals['_URLDIRECTIVE']._serialized_end=540
# @@protoc_insertion_point(module_scope)
