# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/loopback_server.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/loopback_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import sync_entity_pb2 as components_dot_sync_dot_protocol_dot_sync__entity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.components/sync/protocol/loopback_server.proto\x12\x07sync_pb\x1a*components/sync/protocol/sync_entity.proto\"\xcd\x01\n\x14LoopbackServerEntity\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".sync_pb.LoopbackServerEntity.Type\x12#\n\x06\x65ntity\x18\x02 \x01(\x0b\x32\x13.sync_pb.SyncEntity\x12\x11\n\tdata_type\x18\x03 \x01(\x03\"K\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08\x42OOKMARK\x10\x01\x12\r\n\tPERMANENT\x10\x02\x12\r\n\tTOMBSTONE\x10\x03\x12\n\n\x06UNIQUE\x10\x04\"\xa5\x01\n\x13LoopbackServerProto\x12\x0f\n\x07version\x18\x01 \x01(\x03\x12\x16\n\x0estore_birthday\x18\x02 \x01(\x03\x12/\n\x08\x65ntities\x18\x03 \x03(\x0b\x32\x1d.sync_pb.LoopbackServerEntity\x12\x15\n\rkeystore_keys\x18\x04 \x03(\x0c\x12\x1d\n\x15last_version_assigned\x18\x05 \x01(\x03\x42+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.loopback_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_LOOPBACKSERVERENTITY']._serialized_start=104
  _globals['_LOOPBACKSERVERENTITY']._serialized_end=309
  _globals['_LOOPBACKSERVERENTITY_TYPE']._serialized_start=234
  _globals['_LOOPBACKSERVERENTITY_TYPE']._serialized_end=309
  _globals['_LOOPBACKSERVERPROTO']._serialized_start=312
  _globals['_LOOPBACKSERVERPROTO']._serialized_end=477
# @@protoc_insertion_point(module_scope)
