# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/plus_address_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/plus_address_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5components/sync/protocol/plus_address_specifics.proto\x12\x07sync_pb\"a\n\x14PlusAddressSpecifics\x12\x12\n\nprofile_id\x18\x01 \x01(\t\x12\r\n\x05\x66\x61\x63\x65t\x18\x02 \x01(\t\x12&\n\nplus_email\x18\x03 \x01(\x0b\x32\x12.sync_pb.PlusEmail\"\"\n\tPlusEmail\x12\x15\n\remail_address\x18\x01 \x01(\tB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.plus_address_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_PLUSADDRESSSPECIFICS']._serialized_start=66
  _globals['_PLUSADDRESSSPECIFICS']._serialized_end=163
  _globals['_PLUSEMAIL']._serialized_start=165
  _globals['_PLUSEMAIL']._serialized_end=199
# @@protoc_insertion_point(module_scope)
