# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/power_bookmark_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/power_bookmark_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import note_entity_pb2 as components_dot_sync_dot_protocol_dot_note__entity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7components/sync/protocol/power_bookmark_specifics.proto\x12\x07sync_pb\x1a*components/sync/protocol/note_entity.proto\"C\n\x0bPowerEntity\x12*\n\x0bnote_entity\x18\x02 \x01(\x0b\x32\x13.sync_pb.NoteEntityH\x00\x42\x08\n\x06\x65ntity\"\xa7\x02\n\x16PowerBookmarkSpecifics\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12=\n\npower_type\x18\x03 \x01(\x0e\x32).sync_pb.PowerBookmarkSpecifics.PowerType\x12\x1a\n\x12\x63reation_time_usec\x18\x04 \x01(\x03\x12\x18\n\x10update_time_usec\x18\x05 \x01(\x03\x12*\n\x0cpower_entity\x18\x64 \x01(\x0b\x32\x14.sync_pb.PowerEntity\"Q\n\tPowerType\x12\x1a\n\x16POWER_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fPOWER_TYPE_MOCK\x10\x01\x12\x13\n\x0fPOWER_TYPE_NOTE\x10\x02\x42+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.power_bookmark_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_POWERENTITY']._serialized_start=112
  _globals['_POWERENTITY']._serialized_end=179
  _globals['_POWERBOOKMARKSPECIFICS']._serialized_start=182
  _globals['_POWERBOOKMARKSPECIFICS']._serialized_end=477
  _globals['_POWERBOOKMARKSPECIFICS_POWERTYPE']._serialized_start=396
  _globals['_POWERBOOKMARKSPECIFICS_POWERTYPE']._serialized_end=477
# @@protoc_insertion_point(module_scope)
