# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/printer_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/printer_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0components/sync/protocol/printer_specifics.proto\x12\x07sync_pb\"\xb0\x01\n\x13PrinterPPDReference\x12\x1d\n\x15user_supplied_ppd_url\x18\x01 \x01(\t\x12\"\n\x16\x65\x66\x66\x65\x63tive_manufacturer\x18\x02 \x01(\tB\x02\x18\x01\x12\x1b\n\x0f\x65\x66\x66\x65\x63tive_model\x18\x03 \x01(\tB\x02\x18\x01\x12 \n\x18\x65\x66\x66\x65\x63tive_make_and_model\x18\x04 \x01(\t\x12\x17\n\x08\x61utoconf\x18\x05 \x01(\x08:\x05\x66\x61lse\"\xa4\x02\n\x10PrinterSpecifics\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x18\n\x0cmanufacturer\x18\x04 \x01(\tB\x02\x18\x01\x12\x11\n\x05model\x18\x05 \x01(\tB\x02\x18\x01\x12\x0b\n\x03uri\x18\x06 \x01(\t\x12\x0c\n\x04uuid\x18\x07 \x01(\t\x12\x0f\n\x03ppd\x18\x08 \x01(\x0c\x42\x02\x18\x01\x12\x33\n\rppd_reference\x18\t \x01(\x0b\x32\x1c.sync_pb.PrinterPPDReference\x12\x19\n\x11updated_timestamp\x18\n \x01(\x03\x12\x16\n\x0emake_and_model\x18\x0b \x01(\t\x12\x18\n\x10print_server_uri\x18\x0c \x01(\tB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.printer_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_PRINTERPPDREFERENCE'].fields_by_name['effective_manufacturer']._loaded_options = None
  _globals['_PRINTERPPDREFERENCE'].fields_by_name['effective_manufacturer']._serialized_options = b'\030\001'
  _globals['_PRINTERPPDREFERENCE'].fields_by_name['effective_model']._loaded_options = None
  _globals['_PRINTERPPDREFERENCE'].fields_by_name['effective_model']._serialized_options = b'\030\001'
  _globals['_PRINTERSPECIFICS'].fields_by_name['manufacturer']._loaded_options = None
  _globals['_PRINTERSPECIFICS'].fields_by_name['manufacturer']._serialized_options = b'\030\001'
  _globals['_PRINTERSPECIFICS'].fields_by_name['model']._loaded_options = None
  _globals['_PRINTERSPECIFICS'].fields_by_name['model']._serialized_options = b'\030\001'
  _globals['_PRINTERSPECIFICS'].fields_by_name['ppd']._loaded_options = None
  _globals['_PRINTERSPECIFICS'].fields_by_name['ppd']._serialized_options = b'\030\001'
  _globals['_PRINTERPPDREFERENCE']._serialized_start=62
  _globals['_PRINTERPPDREFERENCE']._serialized_end=238
  _globals['_PRINTERSPECIFICS']._serialized_start=241
  _globals['_PRINTERSPECIFICS']._serialized_end=533
# @@protoc_insertion_point(module_scope)
