# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/product_comparison_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/product_comparison_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import unique_position_pb2 as components_dot_sync_dot_protocol_dot_unique__position__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;components/sync/protocol/product_comparison_specifics.proto\x12\x07sync_pb\x1a.components/sync/protocol/unique_position.proto\"\xb6\x02\n\x1aProductComparisonSpecifics\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\'\n\x1f\x63reation_time_unix_epoch_millis\x18\x02 \x01(\x03\x12%\n\x1dupdate_time_unix_epoch_millis\x18\x03 \x01(\x03\x12\x0c\n\x04name\x18\x04 \x01(\t\x12%\n\x04\x64\x61ta\x18\x05 \x03(\x0b\x32\x17.sync_pb.ComparisonData\x12\x38\n\x12product_comparison\x18\x06 \x01(\x0b\x32\x1a.sync_pb.ProductComparisonH\x00\x12\x41\n\x17product_comparison_item\x18\x07 \x01(\x0b\x32\x1e.sync_pb.ProductComparisonItemH\x00\x42\x08\n\x06\x65ntity\"\x1d\n\x0e\x43omparisonData\x12\x0b\n\x03url\x18\x01 \x01(\t\"!\n\x11ProductComparison\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x86\x01\n\x15ProductComparisonItem\x12\x1f\n\x17product_comparison_uuid\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x30\n\x0funique_position\x18\x03 \x01(\x0b\x32\x17.sync_pb.UniquePosition\x12\r\n\x05title\x18\x04 \x01(\tB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.product_comparison_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_PRODUCTCOMPARISONSPECIFICS']._serialized_start=121
  _globals['_PRODUCTCOMPARISONSPECIFICS']._serialized_end=431
  _globals['_COMPARISONDATA']._serialized_start=433
  _globals['_COMPARISONDATA']._serialized_end=462
  _globals['_PRODUCTCOMPARISON']._serialized_start=464
  _globals['_PRODUCTCOMPARISON']._serialized_end=497
  _globals['_PRODUCTCOMPARISONITEM']._serialized_start=500
  _globals['_PRODUCTCOMPARISONITEM']._serialized_end=634
# @@protoc_insertion_point(module_scope)
