# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/reading_list_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/reading_list_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5components/sync/protocol/reading_list_specifics.proto\x12\x07sync_pb\"\xd7\x02\n\x14ReadingListSpecifics\x12\x10\n\x08\x65ntry_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x18\n\x10\x63reation_time_us\x18\x04 \x01(\x03\x12\x16\n\x0eupdate_time_us\x18\x05 \x01(\x03\x12\x1a\n\x12\x66irst_read_time_us\x18\x07 \x01(\x03\x12\x1c\n\x14update_title_time_us\x18\x08 \x01(\x03\x12#\n\x1b\x65stimated_read_time_seconds\x18\t \x01(\x05\x12\x44\n\x06status\x18\x06 \x01(\x0e\x32\x34.sync_pb.ReadingListSpecifics.ReadingListEntryStatus\":\n\x16ReadingListEntryStatus\x12\n\n\x06UNREAD\x10\x00\x12\x08\n\x04READ\x10\x01\x12\n\n\x06UNSEEN\x10\x02\x42+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.reading_list_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_READINGLISTSPECIFICS']._serialized_start=67
  _globals['_READINGLISTSPECIFICS']._serialized_end=410
  _globals['_READINGLISTSPECIFICS_READINGLISTENTRYSTATUS']._serialized_start=352
  _globals['_READINGLISTSPECIFICS_READINGLISTENTRYSTATUS']._serialized_end=410
# @@protoc_insertion_point(module_scope)
