# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/saved_tab_group_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/saved_tab_group_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import tab_group_attribution_metadata_pb2 as components_dot_sync_dot_protocol_dot_tab__group__attribution__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8components/sync/protocol/saved_tab_group_specifics.proto\x12\x07sync_pb\x1a=components/sync/protocol/tab_group_attribution_metadata.proto\"\x87\x04\n\rSavedTabGroup\x12\x10\n\x08position\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x38\n\x05\x63olor\x18\x03 \x01(\x0e\x32).sync_pb.SavedTabGroup.SavedTabGroupColor\x12\x17\n\x0fpinned_position\x18\x04 \x01(\x03\x12\x18\n\x10\x62ookmark_node_id\x18\x06 \x01(\t\"\xe1\x02\n\x12SavedTabGroupColor\x12%\n!SAVED_TAB_GROUP_COLOR_UNSPECIFIED\x10\x00\x12\x1e\n\x1aSAVED_TAB_GROUP_COLOR_GREY\x10\x01\x12\x1e\n\x1aSAVED_TAB_GROUP_COLOR_BLUE\x10\x02\x12\x1d\n\x19SAVED_TAB_GROUP_COLOR_RED\x10\x03\x12 \n\x1cSAVED_TAB_GROUP_COLOR_YELLOW\x10\x04\x12\x1f\n\x1bSAVED_TAB_GROUP_COLOR_GREEN\x10\x05\x12\x1e\n\x1aSAVED_TAB_GROUP_COLOR_PINK\x10\x06\x12 \n\x1cSAVED_TAB_GROUP_COLOR_PURPLE\x10\x07\x12\x1e\n\x1aSAVED_TAB_GROUP_COLOR_CYAN\x10\x08\x12 \n\x1cSAVED_TAB_GROUP_COLOR_ORANGE\x10\tJ\x04\x08\x05\x10\x06\"T\n\x10SavedTabGroupTab\x12\x12\n\ngroup_guid\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x01(\x03\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\"\xa6\x02\n\x16SavedTabGroupSpecifics\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12*\n\"creation_time_windows_epoch_micros\x18\x02 \x01(\x03\x12(\n update_time_windows_epoch_micros\x18\x03 \x01(\x03\x12\'\n\x05group\x18\x04 \x01(\x0b\x32\x16.sync_pb.SavedTabGroupH\x00\x12(\n\x03tab\x18\x05 \x01(\x0b\x32\x19.sync_pb.SavedTabGroupTabH\x00\x12:\n\x14\x61ttribution_metadata\x18\x06 \x01(\x0b\x32\x1c.sync_pb.AttributionMetadata\x12\x0f\n\x07version\x18\x07 \x01(\x05\x42\x08\n\x06\x65ntityB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.saved_tab_group_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_SAVEDTABGROUP']._serialized_start=133
  _globals['_SAVEDTABGROUP']._serialized_end=652
  _globals['_SAVEDTABGROUP_SAVEDTABGROUPCOLOR']._serialized_start=293
  _globals['_SAVEDTABGROUP_SAVEDTABGROUPCOLOR']._serialized_end=646
  _globals['_SAVEDTABGROUPTAB']._serialized_start=654
  _globals['_SAVEDTABGROUPTAB']._serialized_end=738
  _globals['_SAVEDTABGROUPSPECIFICS']._serialized_start=741
  _globals['_SAVEDTABGROUPSPECIFICS']._serialized_end=1035
# @@protoc_insertion_point(module_scope)
