# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/search_engine_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/search_engine_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6components/sync/protocol/search_engine_specifics.proto\x12\x07sync_pb\"\xcc\x06\n\x15SearchEngineSpecifics\x12\x12\n\nshort_name\x18\x01 \x01(\t\x12\x0f\n\x07keyword\x18\x02 \x01(\t\x12\x13\n\x0b\x66\x61vicon_url\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x1c\n\x14safe_for_autoreplace\x18\x05 \x01(\x08\x12\x17\n\x0foriginating_url\x18\x06 \x01(\t\x12\x14\n\x0c\x64\x61te_created\x18\x07 \x01(\x03\x12\x17\n\x0finput_encodings\x18\x08 \x01(\t\x12+\n\x1f\x64\x65precated_show_in_default_list\x18\t \x01(\x08\x42\x02\x18\x01\x12\x17\n\x0fsuggestions_url\x18\n \x01(\t\x12\x16\n\x0eprepopulate_id\x18\x0b \x01(\x05\x12 \n\x14\x61utogenerate_keyword\x18\x0c \x01(\x08\x42\x02\x18\x01\x12\x17\n\x0binstant_url\x18\x0f \x01(\tB\x02\x18\x01\x12\x15\n\rlast_modified\x18\x11 \x01(\x03\x12\x11\n\tsync_guid\x18\x12 \x01(\t\x12\x16\n\x0e\x61lternate_urls\x18\x13 \x03(\t\x12(\n\x1csearch_terms_replacement_key\x18\x14 \x01(\tB\x02\x18\x01\x12\x11\n\timage_url\x18\x15 \x01(\t\x12\x1e\n\x16search_url_post_params\x18\x16 \x01(\t\x12#\n\x1bsuggestions_url_post_params\x18\x17 \x01(\t\x12#\n\x17instant_url_post_params\x18\x18 \x01(\tB\x02\x18\x01\x12\x1d\n\x15image_url_post_params\x18\x19 \x01(\t\x12\x13\n\x0bnew_tab_url\x18\x1a \x01(\t\x12>\n\tis_active\x18\x1b \x01(\x0e\x32+.sync_pb.SearchEngineSpecifics.ActiveStatus\x12\x17\n\x0fstarter_pack_id\x18\x1c \x01(\x05\"^\n\x0c\x41\x63tiveStatus\x12\x1d\n\x19\x41\x43TIVE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n\x12\x41\x43TIVE_STATUS_TRUE\x10\x01\x12\x17\n\x13\x41\x43TIVE_STATUS_FALSE\x10\x02J\x04\x08\x0e\x10\x0fR\x11\x63reated_by_policyB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.search_engine_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_SEARCHENGINESPECIFICS'].fields_by_name['deprecated_show_in_default_list']._loaded_options = None
  _globals['_SEARCHENGINESPECIFICS'].fields_by_name['deprecated_show_in_default_list']._serialized_options = b'\030\001'
  _globals['_SEARCHENGINESPECIFICS'].fields_by_name['autogenerate_keyword']._loaded_options = None
  _globals['_SEARCHENGINESPECIFICS'].fields_by_name['autogenerate_keyword']._serialized_options = b'\030\001'
  _globals['_SEARCHENGINESPECIFICS'].fields_by_name['instant_url']._loaded_options = None
  _globals['_SEARCHENGINESPECIFICS'].fields_by_name['instant_url']._serialized_options = b'\030\001'
  _globals['_SEARCHENGINESPECIFICS'].fields_by_name['search_terms_replacement_key']._loaded_options = None
  _globals['_SEARCHENGINESPECIFICS'].fields_by_name['search_terms_replacement_key']._serialized_options = b'\030\001'
  _globals['_SEARCHENGINESPECIFICS'].fields_by_name['instant_url_post_params']._loaded_options = None
  _globals['_SEARCHENGINESPECIFICS'].fields_by_name['instant_url_post_params']._serialized_options = b'\030\001'
  _globals['_SEARCHENGINESPECIFICS']._serialized_start=68
  _globals['_SEARCHENGINESPECIFICS']._serialized_end=912
  _globals['_SEARCHENGINESPECIFICS_ACTIVESTATUS']._serialized_start=793
  _globals['_SEARCHENGINESPECIFICS_ACTIVESTATUS']._serialized_end=887
# @@protoc_insertion_point(module_scope)
