# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/security_event_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/security_event_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import gaia_password_reuse_pb2 as components_dot_sync_dot_protocol_dot_gaia__password__reuse__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7components/sync/protocol/security_event_specifics.proto\x12\x07sync_pb\x1a\x32\x63omponents/sync/protocol/gaia_password_reuse.proto\"{\n\x16SecurityEventSpecifics\x12?\n\x19gaia_password_reuse_event\x18\x01 \x01(\x0b\x32\x1a.sync_pb.GaiaPasswordReuseH\x00\x12\x17\n\x0f\x65vent_time_usec\x18\x02 \x01(\x03\x42\x07\n\x05\x65ventB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.security_event_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_SECURITYEVENTSPECIFICS']._serialized_start=120
  _globals['_SECURITYEVENTSPECIFICS']._serialized_end=243
# @@protoc_insertion_point(module_scope)
