# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/shared_comment_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/shared_comment_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7components/sync/protocol/shared_comment_specifics.proto\x12\x07sync_pb\"\x9f\x02\n\x10SharedUrlContext\x12\x44\n\x0frepresentations\x18\x01 \x03(\x0b\x32+.sync_pb.SharedUrlContext.UrlRepresentation\x12\r\n\x05title\x18\x02 \x01(\t\x1a\x65\n\x11UrlRepresentation\x12\x30\n\x06source\x18\x01 \x01(\x0e\x32 .sync_pb.SharedUrlContext.Source\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\"O\n\x06Source\x12\x16\n\x12SOURCE_UNSPECIFIED\x10\x00\x12\x0b\n\x07OMNIBOX\x10\x01\x12\r\n\tFROM_SYNC\x10\x02\x12\x11\n\rCANONICAL_URL\x10\x03\"\xb7\x04\n\x0b\x43ommentData\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x35\n\x0b\x61ttribution\x18\x02 \x01(\x0b\x32 .sync_pb.CommentData.Attribution\x12\x30\n\torder_key\x18\x03 \x01(\x0b\x32\x1d.sync_pb.CommentData.OrderKey\x1a\xf7\x02\n\x0b\x41ttribution\x12\x43\n\ttop_level\x18\x01 \x01(\x0b\x32..sync_pb.CommentData.Attribution.CommentTargetH\x00\x12<\n\x06parent\x18\x02 \x01(\x0b\x32*.sync_pb.CommentData.Attribution.InReplyToH\x00\x1a\xbc\x01\n\rCommentTarget\x12\x1f\n\x17shared_url_context_uuid\x18\x01 \x01(\t\x12R\n\rlink_fragment\x18\x02 \x01(\x0b\x32;.sync_pb.CommentData.Attribution.CommentTarget.FragmentLink\x1a\x36\n\x0c\x46ragmentLink\x12\x10\n\x08\x66ragment\x18\x01 \x01(\t\x12\x14\n\x0ctext_preview\x18\x02 \x01(\t\x1a\x1e\n\tInReplyTo\x12\x11\n\tparent_id\x18\x01 \x01(\tB\x06\n\x04kind\x1a\x37\n\x08OrderKey\x12\x13\n\x0b\x64\x65vice_guid\x18\x01 \x01(\t\x12\x16\n\x0elocal_sequence\x18\x02 \x01(\x03\"\xbd\x01\n\x16SharedCommentSpecifics\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x12\n\ncontext_id\x18\x02 \x01(\t\x12\x15\n\rproto_version\x18\x03 \x01(\x03\x12\'\n\x07\x63omment\x18\x04 \x01(\x0b\x32\x14.sync_pb.CommentDataH\x00\x12\x37\n\x12shared_url_context\x18\x05 \x01(\x0b\x32\x19.sync_pb.SharedUrlContextH\x00\x42\x08\n\x06\x65ntityB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.shared_comment_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_SHAREDURLCONTEXT']._serialized_start=69
  _globals['_SHAREDURLCONTEXT']._serialized_end=356
  _globals['_SHAREDURLCONTEXT_URLREPRESENTATION']._serialized_start=174
  _globals['_SHAREDURLCONTEXT_URLREPRESENTATION']._serialized_end=275
  _globals['_SHAREDURLCONTEXT_SOURCE']._serialized_start=277
  _globals['_SHAREDURLCONTEXT_SOURCE']._serialized_end=356
  _globals['_COMMENTDATA']._serialized_start=359
  _globals['_COMMENTDATA']._serialized_end=926
  _globals['_COMMENTDATA_ATTRIBUTION']._serialized_start=494
  _globals['_COMMENTDATA_ATTRIBUTION']._serialized_end=869
  _globals['_COMMENTDATA_ATTRIBUTION_COMMENTTARGET']._serialized_start=641
  _globals['_COMMENTDATA_ATTRIBUTION_COMMENTTARGET']._serialized_end=829
  _globals['_COMMENTDATA_ATTRIBUTION_COMMENTTARGET_FRAGMENTLINK']._serialized_start=775
  _globals['_COMMENTDATA_ATTRIBUTION_COMMENTTARGET_FRAGMENTLINK']._serialized_end=829
  _globals['_COMMENTDATA_ATTRIBUTION_INREPLYTO']._serialized_start=831
  _globals['_COMMENTDATA_ATTRIBUTION_INREPLYTO']._serialized_end=861
  _globals['_COMMENTDATA_ORDERKEY']._serialized_start=871
  _globals['_COMMENTDATA_ORDERKEY']._serialized_end=926
  _globals['_SHAREDCOMMENTSPECIFICS']._serialized_start=929
  _globals['_SHAREDCOMMENTSPECIFICS']._serialized_end=1118
# @@protoc_insertion_point(module_scope)
