# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/shared_tab_group_account_data_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/shared_tab_group_account_data_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFcomponents/sync/protocol/shared_tab_group_account_data_specifics.proto\x12\x07sync_pb\"\x8e\x02\n\"SharedTabGroupAccountDataSpecifics\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x18\n\x10\x63ollaboration_id\x18\x02 \x01(\t\x12\x37\n\x12shared_tab_details\x18\x03 \x01(\x0b\x32\x19.sync_pb.SharedTabDetailsH\x00\x12\x42\n\x18shared_tab_group_details\x18\x04 \x01(\x0b\x32\x1e.sync_pb.SharedTabGroupDetailsH\x00\x12(\n update_time_windows_epoch_micros\x18\x05 \x01(\x03\x12\x0f\n\x07version\x18\x06 \x01(\x05\x42\x08\n\x06\x65ntity\"\\\n\x10SharedTabDetails\x12\x1d\n\x15shared_tab_group_guid\x18\x01 \x01(\t\x12)\n!last_seen_timestamp_windows_epoch\x18\x02 \x01(\x03\"0\n\x15SharedTabGroupDetails\x12\x17\n\x0fpinned_position\x18\x01 \x01(\x03\x42+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.shared_tab_group_account_data_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_SHAREDTABGROUPACCOUNTDATASPECIFICS']._serialized_start=84
  _globals['_SHAREDTABGROUPACCOUNTDATASPECIFICS']._serialized_end=354
  _globals['_SHAREDTABDETAILS']._serialized_start=356
  _globals['_SHAREDTABDETAILS']._serialized_end=448
  _globals['_SHAREDTABGROUPDETAILS']._serialized_start=450
  _globals['_SHAREDTABGROUPDETAILS']._serialized_end=498
# @@protoc_insertion_point(module_scope)
