# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/shared_tab_group_data_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/shared_tab_group_data_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import unique_position_pb2 as components_dot_sync_dot_protocol_dot_unique__position__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>components/sync/protocol/shared_tab_group_data_specifics.proto\x12\x07sync_pb\x1a.components/sync/protocol/unique_position.proto\"\xc7\x01\n\x1bSharedTabGroupDataSpecifics\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12,\n\ttab_group\x18\x03 \x01(\x0b\x32\x17.sync_pb.SharedTabGroupH\x00\x12!\n\x03tab\x18\x04 \x01(\x0b\x32\x12.sync_pb.SharedTabH\x00\x12(\n update_time_windows_epoch_micros\x18\x05 \x01(\x03\x12\x0f\n\x07version\x18\x06 \x01(\x05\x42\x08\n\x06\x65ntityJ\x04\x08\x02\x10\x03\"\xeb\x01\n\x0eSharedTabGroup\x12\r\n\x05title\x18\x01 \x01(\t\x12,\n\x05\x63olor\x18\x02 \x01(\x0e\x32\x1d.sync_pb.SharedTabGroup.Color\x12\"\n\x1aoriginating_tab_group_guid\x18\x03 \x01(\t\"x\n\x05\x43olor\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x08\n\x04GREY\x10\x01\x12\x08\n\x04\x42LUE\x10\x02\x12\x07\n\x03RED\x10\x03\x12\n\n\x06YELLOW\x10\x04\x12\t\n\x05GREEN\x10\x05\x12\x08\n\x04PINK\x10\x06\x12\n\n\x06PURPLE\x10\x07\x12\x08\n\x04\x43YAN\x10\x08\x12\n\n\x06ORANGE\x10\t\"\x8b\x01\n\tSharedTab\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x1d\n\x15shared_tab_group_guid\x18\x04 \x01(\t\x12\x30\n\x0funique_position\x18\x05 \x01(\x0b\x32\x17.sync_pb.UniquePositionJ\x04\x08\x03\x10\x04R\x0b\x66\x61vicon_urlB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.shared_tab_group_data_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_SHAREDTABGROUPDATASPECIFICS']._serialized_start=124
  _globals['_SHAREDTABGROUPDATASPECIFICS']._serialized_end=323
  _globals['_SHAREDTABGROUP']._serialized_start=326
  _globals['_SHAREDTABGROUP']._serialized_end=561
  _globals['_SHAREDTABGROUP_COLOR']._serialized_start=441
  _globals['_SHAREDTABGROUP_COLOR']._serialized_end=561
  _globals['_SHAREDTAB']._serialized_start=564
  _globals['_SHAREDTAB']._serialized_end=703
# @@protoc_insertion_point(module_scope)
