# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/sync_invalidations_payload.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/sync_invalidations_payload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9components/sync/protocol/sync_invalidations_payload.proto\x12\x07sync_pb\"\xc0\x01\n\x18SyncInvalidationsPayload\x12W\n\x17\x64\x61ta_type_invalidations\x18\x01 \x03(\x0b\x32\x36.sync_pb.SyncInvalidationsPayload.DataTypeInvalidation\x12\x0c\n\x04hint\x18\x02 \x01(\x0c\x12\x0f\n\x07version\x18\x03 \x01(\x03\x1a,\n\x14\x44\x61taTypeInvalidation\x12\x14\n\x0c\x64\x61ta_type_id\x18\x01 \x01(\x05\x42+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.sync_invalidations_payload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_SYNCINVALIDATIONSPAYLOAD']._serialized_start=71
  _globals['_SYNCINVALIDATIONSPAYLOAD']._serialized_end=263
  _globals['_SYNCINVALIDATIONSPAYLOAD_DATATYPEINVALIDATION']._serialized_start=219
  _globals['_SYNCINVALIDATIONSPAYLOAD_DATATYPEINVALIDATION']._serialized_end=263
# @@protoc_insertion_point(module_scope)
