# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/sync_collaboration_attribution.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/sync_collaboration_attribution.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=components/sync/protocol/sync_collaboration_attribution.proto\x12\x07sync_pb\x1a google/protobuf/descriptor.proto\"\xb5\x01\n\x1cSyncCollaborationAttribution\x12O\n\x10\x61ttribution_type\x18\x01 \x01(\x0e\x32\x35.sync_pb.SyncCollaborationAttribution.AttributionType\x12\x0c\n\x04name\x18\x02 \x01(\t\"6\n\x0f\x41ttributionType\x12\x08\n\x04NONE\x10\x00\x12\x19\n\x15LAST_MODIFIED_BY_USER\x10\x01:p\n\x1esync_collaboration_attribution\x12\x1d.google.protobuf.FieldOptions\x18\xdd\xdd\xbe\xff\x01 \x01(\x0b\x32%.sync_pb.SyncCollaborationAttributionB)\n%org.chromium.components.sync.protocolP\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.sync_collaboration_attribution_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolP\001'
  _globals['_SYNCCOLLABORATIONATTRIBUTION']._serialized_start=109
  _globals['_SYNCCOLLABORATIONATTRIBUTION']._serialized_end=290
  _globals['_SYNCCOLLABORATIONATTRIBUTION_ATTRIBUTIONTYPE']._serialized_start=236
  _globals['_SYNCCOLLABORATIONATTRIBUTION_ATTRIBUTIONTYPE']._serialized_end=290
# @@protoc_insertion_point(module_scope)
