# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/tab_group_attribution_metadata.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/tab_group_attribution_metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=components/sync/protocol/tab_group_attribution_metadata.proto\x12\x07sync_pb\"\x9d\x02\n\x13\x41ttributionMetadata\x12\x39\n\x07\x63reated\x18\x01 \x01(\x0b\x32(.sync_pb.AttributionMetadata.Attribution\x12\x39\n\x07updated\x18\x02 \x01(\x0b\x32(.sync_pb.AttributionMetadata.Attribution\x1a\x8f\x01\n\x0b\x41ttribution\x12S\n\x0b\x64\x65vice_info\x18\x01 \x01(\x0b\x32>.sync_pb.AttributionMetadata.Attribution.AttributionDeviceInfo\x1a+\n\x15\x41ttributionDeviceInfo\x12\x12\n\ncache_guid\x18\x01 \x01(\tB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.tab_group_attribution_metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_ATTRIBUTIONMETADATA']._serialized_start=75
  _globals['_ATTRIBUTIONMETADATA']._serialized_end=360
  _globals['_ATTRIBUTIONMETADATA_ATTRIBUTION']._serialized_start=217
  _globals['_ATTRIBUTIONMETADATA_ATTRIBUTION']._serialized_end=360
  _globals['_ATTRIBUTIONMETADATA_ATTRIBUTION_ATTRIBUTIONDEVICEINFO']._serialized_start=317
  _globals['_ATTRIBUTIONMETADATA_ATTRIBUTION_ATTRIBUTIONDEVICEINFO']._serialized_end=360
# @@protoc_insertion_point(module_scope)
