# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/test.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#components/sync/protocol/test.proto\x12\x07sync_pb\"!\n\x12UnknownFieldsTestA\x12\x0b\n\x03\x66oo\x18\x01 \x02(\x08\".\n\x12UnknownFieldsTestB\x12\x0b\n\x03\x66oo\x18\x01 \x02(\x08\x12\x0b\n\x03\x62\x61r\x18\x02 \x02(\x08\x42+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_UNKNOWNFIELDSTESTA']._serialized_start=48
  _globals['_UNKNOWNFIELDSTESTA']._serialized_end=81
  _globals['_UNKNOWNFIELDSTESTB']._serialized_start=83
  _globals['_UNKNOWNFIELDSTESTB']._serialized_end=129
# @@protoc_insertion_point(module_scope)
