# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/theme_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/theme_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import theme_types_pb2 as components_dot_sync_dot_protocol_dot_theme__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.components/sync/protocol/theme_specifics.proto\x12\x07sync_pb\x1a*components/sync/protocol/theme_types.proto\"\x8a\x05\n\x0eThemeSpecifics\x12\x18\n\x10use_custom_theme\x18\x01 \x01(\x08\x12#\n\x1buse_system_theme_by_default\x18\x02 \x01(\x08\x12\x19\n\x11\x63ustom_theme_name\x18\x03 \x01(\t\x12\x17\n\x0f\x63ustom_theme_id\x18\x04 \x01(\t\x12\x1f\n\x17\x63ustom_theme_update_url\x18\x05 \x01(\t\x12T\n\x19\x61utogenerated_color_theme\x18\x06 \x01(\x0b\x32/.sync_pb.ThemeSpecifics.AutogeneratedColorThemeH\x00\x12\x33\n\x10user_color_theme\x18\x07 \x01(\x0b\x32\x17.sync_pb.UserColorThemeH\x00\x12@\n\x17grayscale_theme_enabled\x18\x08 \x01(\x0b\x32\x1d.sync_pb.ThemeSpecifics.EmptyH\x00\x12H\n\x14\x62rowser_color_scheme\x18\t \x01(\x0e\x32*.sync_pb.ThemeSpecifics.BrowserColorScheme\x12\x34\n\x0entp_background\x18\n \x01(\x0b\x32\x1c.sync_pb.NtpCustomBackground\x1a(\n\x17\x41utogeneratedColorTheme\x12\r\n\x05\x63olor\x18\x01 \x01(\r\x1a\x07\n\x05\x45mpty\"[\n\x12\x42rowserColorScheme\x12$\n BROWSER_COLOR_SCHEME_UNSPECIFIED\x10\x00\x12\n\n\x06SYSTEM\x10\x01\x12\t\n\x05LIGHT\x10\x02\x12\x08\n\x04\x44\x41RK\x10\x03\x42\x07\n\x05\x63olorB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.theme_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_THEMESPECIFICS']._serialized_start=104
  _globals['_THEMESPECIFICS']._serialized_end=754
  _globals['_THEMESPECIFICS_AUTOGENERATEDCOLORTHEME']._serialized_start=603
  _globals['_THEMESPECIFICS_AUTOGENERATEDCOLORTHEME']._serialized_end=643
  _globals['_THEMESPECIFICS_EMPTY']._serialized_start=645
  _globals['_THEMESPECIFICS_EMPTY']._serialized_end=652
  _globals['_THEMESPECIFICS_BROWSERCOLORSCHEME']._serialized_start=654
  _globals['_THEMESPECIFICS_BROWSERCOLORSCHEME']._serialized_end=745
# @@protoc_insertion_point(module_scope)
