# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/theme_types.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/theme_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*components/sync/protocol/theme_types.proto\x12\x07sync_pb\"\xf0\x01\n\x0eUserColorTheme\x12\r\n\x05\x63olor\x18\x01 \x01(\r\x12J\n\x15\x62rowser_color_variant\x18\x02 \x01(\x0e\x32+.sync_pb.UserColorTheme.BrowserColorVariant\"\x82\x01\n\x13\x42rowserColorVariant\x12%\n!BROWSER_COLOR_VARIANT_UNSPECIFIED\x10\x00\x12\n\n\x06SYSTEM\x10\x01\x12\x0e\n\nTONAL_SPOT\x10\x02\x12\x0b\n\x07NEUTRAL\x10\x03\x12\x0b\n\x07VIBRANT\x10\x04\x12\x0e\n\nEXPRESSIVE\x10\x05\"\xe9\x01\n\x13NtpCustomBackground\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x1a\n\x12\x61ttribution_line_1\x18\x02 \x01(\t\x12\x1a\n\x12\x61ttribution_line_2\x18\x03 \x01(\t\x12\x1e\n\x16\x61ttribution_action_url\x18\x04 \x01(\t\x12\x15\n\rcollection_id\x18\x05 \x01(\t\x12\x14\n\x0cresume_token\x18\x06 \x01(\t\x12,\n$refresh_timestamp_unix_epoch_seconds\x18\x07 \x01(\x03\x12\x12\n\nmain_color\x18\x08 \x01(\rB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.theme_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_USERCOLORTHEME']._serialized_start=56
  _globals['_USERCOLORTHEME']._serialized_end=296
  _globals['_USERCOLORTHEME_BROWSERCOLORVARIANT']._serialized_start=166
  _globals['_USERCOLORTHEME_BROWSERCOLORVARIANT']._serialized_end=296
  _globals['_NTPCUSTOMBACKGROUND']._serialized_start=299
  _globals['_NTPCUSTOMBACKGROUND']._serialized_end=532
# @@protoc_insertion_point(module_scope)
