# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/theme_specifics_ios.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/theme_specifics_ios.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from components.sync.protocol import theme_types_pb2 as components_dot_sync_dot_protocol_dot_theme__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2components/sync/protocol/theme_specifics_ios.proto\x12\x07sync_pb\x1a*components/sync/protocol/theme_types.proto\"|\n\x11ThemeSpecificsIos\x12\x31\n\x10user_color_theme\x18\x01 \x01(\x0b\x32\x17.sync_pb.UserColorTheme\x12\x34\n\x0entp_background\x18\x02 \x01(\x0b\x32\x1c.sync_pb.NtpCustomBackgroundB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.theme_specifics_ios_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_THEMESPECIFICSIOS']._serialized_start=107
  _globals['_THEMESPECIFICSIOS']._serialized_end=231
# @@protoc_insertion_point(module_scope)
