# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/typed_url_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/typed_url_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2components/sync/protocol/typed_url_specifics.proto\x12\x07sync_pb\"\xa7\x01\n\x11TypedUrlSpecifics\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06hidden\x18\x04 \x01(\x08\x12\x12\n\x06visits\x18\x07 \x03(\x03\x42\x02\x10\x01\x12\x1d\n\x11visit_transitions\x18\x08 \x03(\x05\x42\x02\x10\x01J\x04\x08\x03\x10\x04J\x04\x08\x05\x10\x06J\x04\x08\x06\x10\x07R\x0btyped_countR\x05visitR\rvisited_countB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.typed_url_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_TYPEDURLSPECIFICS'].fields_by_name['visits']._loaded_options = None
  _globals['_TYPEDURLSPECIFICS'].fields_by_name['visits']._serialized_options = b'\020\001'
  _globals['_TYPEDURLSPECIFICS'].fields_by_name['visit_transitions']._loaded_options = None
  _globals['_TYPEDURLSPECIFICS'].fields_by_name['visit_transitions']._serialized_options = b'\020\001'
  _globals['_TYPEDURLSPECIFICS']._serialized_start=64
  _globals['_TYPEDURLSPECIFICS']._serialized_end=231
# @@protoc_insertion_point(module_scope)
