# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/unencrypted_sharing_message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/unencrypted_sharing_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:components/sync/protocol/unencrypted_sharing_message.proto\x12\x07sync_pb\"\x8f\x01\n\x19UnencryptedSharingMessage\x12\x13\n\x0bsender_guid\x18\x01 \x01(\t\x12\x36\n\x10send_tab_message\x18\x02 \x01(\x0b\x32\x1a.sync_pb.SendTabToSelfPushH\x00\x12\x1a\n\x12sender_device_name\x18\x03 \x01(\tB\t\n\x07payload\"\xa4\x02\n\x11SendTabToSelfPush\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12.\n\x04icon\x18\x03 \x03(\x0b\x32 .sync_pb.SendTabToSelfPush.Image\x12\x31\n\x07\x66\x61vicon\x18\x04 \x01(\x0b\x32 .sync_pb.SendTabToSelfPush.Image\x12\x17\n\x0f\x64\x65stination_url\x18\x05 \x01(\t\x12\x19\n\x11placeholder_title\x18\x06 \x01(\t\x12\x18\n\x10placeholder_body\x18\x07 \x01(\t\x12\x19\n\x11\x65ntry_unique_guid\x18\x08 \x01(\t\x1a&\n\x05Image\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x10\n\x08\x61lt_text\x18\x02 \x01(\tB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.unencrypted_sharing_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_UNENCRYPTEDSHARINGMESSAGE']._serialized_start=72
  _globals['_UNENCRYPTEDSHARINGMESSAGE']._serialized_end=215
  _globals['_SENDTABTOSELFPUSH']._serialized_start=218
  _globals['_SENDTABTOSELFPUSH']._serialized_end=510
  _globals['_SENDTABTOSELFPUSH_IMAGE']._serialized_start=472
  _globals['_SENDTABTOSELFPUSH_IMAGE']._serialized_end=510
# @@protoc_insertion_point(module_scope)
