# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/web_app_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/web_app_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0components/sync/protocol/web_app_specifics.proto\x12\x07sync_pb\"\xa6\x01\n\x0eWebAppIconInfo\x12\x12\n\nsize_in_px\x18\x01 \x01(\x05\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x30\n\x07purpose\x18\x03 \x01(\x0e\x32\x1f.sync_pb.WebAppIconInfo.Purpose\"A\n\x07Purpose\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x07\n\x03\x41NY\x10\x01\x12\x0c\n\x08MASKABLE\x10\x02\x12\x0e\n\nMONOCHROME\x10\x03\"\x9c\x04\n\x0fWebAppSpecifics\x12\x11\n\tstart_url\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12K\n\x19user_display_mode_default\x18\x03 \x01(\x0e\x32(.sync_pb.WebAppSpecifics.UserDisplayMode\x12\x13\n\x0btheme_color\x18\x04 \x01(\r\x12\r\n\x05scope\x18\x05 \x01(\t\x12+\n\nicon_infos\x18\x06 \x03(\x0b\x32\x17.sync_pb.WebAppIconInfo\x12\x19\n\x11user_page_ordinal\x18\x07 \x01(\t\x12\x1b\n\x13user_launch_ordinal\x18\x08 \x01(\t\x12\x1c\n\x14relative_manifest_id\x18\t \x01(\t\x12H\n\x16user_display_mode_cros\x18\n \x01(\x0e\x32(.sync_pb.WebAppSpecifics.UserDisplayMode\x12.\n\rtrusted_icons\x18\x0b \x03(\x0b\x32\x17.sync_pb.WebAppIconInfo\"K\n\x0fUserDisplayMode\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07\x42ROWSER\x10\x01\x12\x0e\n\nSTANDALONE\x10\x03\x12\n\n\x06TABBED\x10\x06R\x1auser_display_mode_non_crosR\x11user_display_modeB+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.web_app_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_WEBAPPICONINFO']._serialized_start=62
  _globals['_WEBAPPICONINFO']._serialized_end=228
  _globals['_WEBAPPICONINFO_PURPOSE']._serialized_start=163
  _globals['_WEBAPPICONINFO_PURPOSE']._serialized_end=228
  _globals['_WEBAPPSPECIFICS']._serialized_start=231
  _globals['_WEBAPPSPECIFICS']._serialized_end=771
  _globals['_WEBAPPSPECIFICS_USERDISPLAYMODE']._serialized_start=649
  _globals['_WEBAPPSPECIFICS_USERDISPLAYMODE']._serialized_end=724
# @@protoc_insertion_point(module_scope)
