# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/web_apk_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/web_apk_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0components/sync/protocol/web_apk_specifics.proto\x12\x07sync_pb\"\xa6\x01\n\x0eWebApkIconInfo\x12\x12\n\nsize_in_px\x18\x01 \x01(\x05\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x30\n\x07purpose\x18\x03 \x01(\x0e\x32\x1f.sync_pb.WebApkIconInfo.Purpose\"A\n\x07Purpose\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x07\n\x03\x41NY\x10\x01\x12\x0c\n\x08MASKABLE\x10\x02\x12\x0e\n\nMONOCHROME\x10\x03\"\xc5\x01\n\x0fWebApkSpecifics\x12\x13\n\x0bmanifest_id\x18\x01 \x01(\t\x12\x11\n\tstart_url\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0btheme_color\x18\x04 \x01(\r\x12\r\n\x05scope\x18\x05 \x01(\t\x12+\n\nicon_infos\x18\x06 \x03(\x0b\x32\x17.sync_pb.WebApkIconInfo\x12+\n#last_used_time_windows_epoch_micros\x18\x07 \x01(\x03\x42+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.web_apk_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_WEBAPKICONINFO']._serialized_start=62
  _globals['_WEBAPKICONINFO']._serialized_end=228
  _globals['_WEBAPKICONINFO_PURPOSE']._serialized_start=163
  _globals['_WEBAPKICONINFO_PURPOSE']._serialized_end=228
  _globals['_WEBAPKSPECIFICS']._serialized_start=231
  _globals['_WEBAPKSPECIFICS']._serialized_end=428
# @@protoc_insertion_point(module_scope)
