# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/sync/protocol/webauthn_credential_specifics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'components/sync/protocol/webauthn_credential_specifics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<components/sync/protocol/webauthn_credential_specifics.proto\x12\x07sync_pb\"\xd1\x05\n\x1bWebauthnCredentialSpecifics\x12\x0f\n\x07sync_id\x18\x01 \x01(\x0c\x12\x15\n\rcredential_id\x18\x02 \x01(\x0c\x12\r\n\x05rp_id\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\x0c\x12%\n\x1dnewly_shadowed_credential_ids\x18\x05 \x03(\x0c\x12\x15\n\rcreation_time\x18\x06 \x01(\x03\x12\x11\n\tuser_name\x18\x07 \x01(\t\x12\x19\n\x11user_display_name\x18\x08 \x01(\t\x12$\n\x1cthird_party_payments_support\x18\x0b \x01(\x08\x12+\n#last_used_time_windows_epoch_micros\x18\r \x01(\x03\x12\x13\n\x0bkey_version\x18\x0e \x01(\x05\x12(\n device_authorization_key_version\x18\x12 \x01(\x05\x12\x15\n\x0bprivate_key\x18\t \x01(\x0cH\x00\x12\x13\n\tencrypted\x18\x0c \x01(\x0cH\x00\x12#\n\x19security_domain_encrypted\x18\x13 \x01(\x0cH\x00\x12\x16\n\x0e\x65\x64ited_by_user\x18\x0f \x01(\x08\x12\x0e\n\x06hidden\x18\x10 \x01(\x08\x12\x13\n\x0bhidden_time\x18\x11 \x01(\x03\x1a\x82\x01\n\tEncrypted\x12\x13\n\x0bprivate_key\x18\x01 \x01(\x0c\x12\x13\n\x0bhmac_secret\x18\x02 \x01(\x0c\x12\x11\n\tcred_blob\x18\x03 \x01(\x0c\x12\x12\n\nlarge_blob\x18\x04 \x01(\x0c\x12$\n\x1clarge_blob_uncompressed_size\x18\x05 \x01(\x04\x1a\x41\n\x17SecurityDomainEncrypted\x12&\n\x1e\x64\x65vice_authorization_encrypted\x18\x01 \x01(\x0c\x42\x10\n\x0e\x65ncrypted_dataJ\x04\x08\n\x10\x0b\x42+\n%org.chromium.components.sync.protocolH\x03P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.sync.protocol.webauthn_credential_specifics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.chromium.components.sync.protocolH\003P\001'
  _globals['_WEBAUTHNCREDENTIALSPECIFICS']._serialized_start=74
  _globals['_WEBAUTHNCREDENTIALSPECIFICS']._serialized_end=795
  _globals['_WEBAUTHNCREDENTIALSPECIFICS_ENCRYPTED']._serialized_start=574
  _globals['_WEBAUTHNCREDENTIALSPECIFICS_ENCRYPTED']._serialized_end=704
  _globals['_WEBAUTHNCREDENTIALSPECIFICS_SECURITYDOMAINENCRYPTED']._serialized_start=706
  _globals['_WEBAUTHNCREDENTIALSPECIFICS_SECURITYDOMAINENCRYPTED']._serialized_end=771
# @@protoc_insertion_point(module_scope)
