# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: content/browser/download/embedder_download_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'content/browser/download/embedder_download_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5content/browser/download/embedder_download_data.proto\x12\rcontent.proto\"_\n\x14\x45mbedderDownloadData\x12G\n\x18storage_partition_config\x18\x01 \x01(\x0b\x32%.content.proto.StoragePartitionConfig\"\xf1\x01\n\x16StoragePartitionConfig\x12\x18\n\x10partition_domain\x18\x01 \x02(\t\x12\x16\n\x0epartition_name\x18\x02 \x02(\t\x12\x11\n\tin_memory\x18\x03 \x02(\x08\x12I\n\rfallback_mode\x18\x04 \x02(\x0e\x32\x32.content.proto.StoragePartitionConfig.FallbackMode\"G\n\x0c\x46\x61llbackMode\x12\t\n\x05kNone\x10\x00\x12\x14\n\x10kPartitionOnDisk\x10\x01\x12\x16\n\x12kPartitionInMemory\x10\x02\x42\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'content.browser.download.embedder_download_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_EMBEDDERDOWNLOADDATA']._serialized_start=72
  _globals['_EMBEDDERDOWNLOADDATA']._serialized_end=167
  _globals['_STORAGEPARTITIONCONFIG']._serialized_start=170
  _globals['_STORAGEPARTITIONCONFIG']._serialized_end=411
  _globals['_STORAGEPARTITIONCONFIG_FALLBACKMODE']._serialized_start=340
  _globals['_STORAGEPARTITIONCONFIG_FALLBACKMODE']._serialized_end=411
# @@protoc_insertion_point(module_scope)
