# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: content/browser/devtools/devtools_background_services.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'content/browser/devtools/devtools_background_services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;content/browser/devtools/devtools_background_services.proto\x12\x16\x63ontent.devtools.proto\"\xf9\x02\n\x16\x42\x61\x63kgroundServiceEvent\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0e\n\x06origin\x18\x02 \x01(\t\x12&\n\x1eservice_worker_registration_id\x18\x03 \x01(\x03\x12\x45\n\x12\x62\x61\x63kground_service\x18\x04 \x01(\x0e\x32).content.devtools.proto.BackgroundService\x12\x12\n\nevent_name\x18\x05 \x01(\t\x12\x13\n\x0binstance_id\x18\x06 \x01(\t\x12Y\n\x0e\x65vent_metadata\x18\x07 \x03(\x0b\x32\x41.content.devtools.proto.BackgroundServiceEvent.EventMetadataEntry\x12\x13\n\x0bstorage_key\x18\x08 \x01(\t\x1a\x34\n\x12\x45ventMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\xcd\x01\n\x11\x42\x61\x63kgroundService\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x1b\n\x17TEST_BACKGROUND_SERVICE\x10\x01\x12\x14\n\x10\x42\x41\x43KGROUND_FETCH\x10\x02\x12\x13\n\x0f\x42\x41\x43KGROUND_SYNC\x10\x03\x12\x12\n\x0ePUSH_MESSAGING\x10\x04\x12\x11\n\rNOTIFICATIONS\x10\x05\x12\x13\n\x0fPAYMENT_HANDLER\x10\x06\x12\x1c\n\x18PERIODIC_BACKGROUND_SYNC\x10\x07\x12\t\n\x05\x43OUNT\x10\x08\x42\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'content.browser.devtools.devtools_background_services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_BACKGROUNDSERVICEEVENT_EVENTMETADATAENTRY']._loaded_options = None
  _globals['_BACKGROUNDSERVICEEVENT_EVENTMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_BACKGROUNDSERVICE']._serialized_start=468
  _globals['_BACKGROUNDSERVICE']._serialized_end=673
  _globals['_BACKGROUNDSERVICEEVENT']._serialized_start=88
  _globals['_BACKGROUNDSERVICEEVENT']._serialized_end=465
  _globals['_BACKGROUNDSERVICEEVENT_EVENTMETADATAENTRY']._serialized_start=413
  _globals['_BACKGROUNDSERVICEEVENT_EVENTMETADATAENTRY']._serialized_end=465
# @@protoc_insertion_point(module_scope)
