# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: content/browser/background_sync/background_sync.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'content/browser/background_sync/background_sync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5content/browser/background_sync/background_sync.proto\x12\x07\x63ontent\"+\n\x13PeriodicSyncOptions\x12\x14\n\x0cmin_interval\x18\x01 \x01(\x03\"\xac\x01\n\x1f\x42\x61\x63kgroundSyncRegistrationProto\x12\x0b\n\x03tag\x18\x02 \x02(\t\x12\x14\n\x0cnum_attempts\x18\x07 \x02(\x05\x12\x13\n\x0b\x64\x65lay_until\x18\x08 \x02(\x03\x12;\n\x15periodic_sync_options\x18\t \x01(\x0b\x32\x1c.content.PeriodicSyncOptions\x12\x14\n\x0cmax_attempts\x18\n \x01(\x05\"r\n BackgroundSyncRegistrationsProto\x12>\n\x0cregistration\x18\x01 \x03(\x0b\x32(.content.BackgroundSyncRegistrationProto\x12\x0e\n\x06origin\x18\x03 \x02(\t*e\n\x10SyncNetworkState\x12\x15\n\x11NETWORK_STATE_ANY\x10\x00\x12 \n\x1cNETWORK_STATE_AVOID_CELLULAR\x10\x01\x12\x18\n\x14NETWORK_STATE_ONLINE\x10\x02\x42\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'content.browser.background_sync.background_sync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_SYNCNETWORKSTATE']._serialized_start=402
  _globals['_SYNCNETWORKSTATE']._serialized_end=503
  _globals['_PERIODICSYNCOPTIONS']._serialized_start=66
  _globals['_PERIODICSYNCOPTIONS']._serialized_end=109
  _globals['_BACKGROUNDSYNCREGISTRATIONPROTO']._serialized_start=112
  _globals['_BACKGROUNDSYNCREGISTRATIONPROTO']._serialized_end=284
  _globals['_BACKGROUNDSYNCREGISTRATIONSPROTO']._serialized_start=286
  _globals['_BACKGROUNDSYNCREGISTRATIONSPROTO']._serialized_end=400
# @@protoc_insertion_point(module_scope)
