# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: content/browser/payments/payment_app.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'content/browser/payments/payment_app.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*content/browser/payments/payment_app.proto\x12\x07\x63ontent\"K\n#StoredPaymentInstrumentKeyInfoProto\x12\x17\n\x0finsertion_order\x18\x01 \x01(\x04\x12\x0b\n\x03key\x18\x02 \x01(\t\"/\n\x0eImageSizeProto\x12\r\n\x05width\x18\x01 \x01(\x04\x12\x0e\n\x06height\x18\x02 \x01(\x04\"g\n\"StoredPaymentInstrumentImageObject\x12\x0b\n\x03src\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12&\n\x05sizes\x18\x03 \x03(\x0b\x32\x17.content.ImageSizeProto\"\x8d\x02\n\x1cStoredPaymentInstrumentProto\x12\x17\n\x0fregistration_id\x18\x01 \x01(\x03\x12\x16\n\x0einstrument_key\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06method\x18\x04 \x01(\t\x12 \n\x18stringified_capabilities\x18\x05 \x01(\t\x12:\n\x05icons\x18\x06 \x03(\x0b\x32+.content.StoredPaymentInstrumentImageObject\x12\x1f\n\x17\x64\x65\x63oded_instrument_icon\x18\x07 \x01(\t\x12\x1f\n\x17supported_card_networks\x18\x08 \x03(\x05\"=\n\x1dStoredRelatedApplicationProto\x12\x10\n\x08platform\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"s\n\x19SupportedDelegationsProto\x12\x18\n\x10shipping_address\x18\x01 \x01(\x08\x12\x12\n\npayer_name\x18\x02 \x01(\x08\x12\x13\n\x0bpayer_phone\x18\x03 \x01(\x08\x12\x13\n\x0bpayer_email\x18\x04 \x01(\x08\"\x9c\x02\n\x15StoredPaymentAppProto\x12\x17\n\x0fregistration_id\x18\x01 \x01(\x03\x12\r\n\x05scope\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04icon\x18\x04 \x01(\t\x12#\n\x1bprefer_related_applications\x18\x05 \x01(\x08\x12\x44\n\x14related_applications\x18\x06 \x03(\x0b\x32&.content.StoredRelatedApplicationProto\x12\x11\n\tuser_hint\x18\x07 \x01(\t\x12\x41\n\x15supported_delegations\x18\x08 \x01(\x0b\x32\".content.SupportedDelegationsProtoB\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'content.browser.payments.payment_app_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_STOREDPAYMENTINSTRUMENTKEYINFOPROTO']._serialized_start=55
  _globals['_STOREDPAYMENTINSTRUMENTKEYINFOPROTO']._serialized_end=130
  _globals['_IMAGESIZEPROTO']._serialized_start=132
  _globals['_IMAGESIZEPROTO']._serialized_end=179
  _globals['_STOREDPAYMENTINSTRUMENTIMAGEOBJECT']._serialized_start=181
  _globals['_STOREDPAYMENTINSTRUMENTIMAGEOBJECT']._serialized_end=284
  _globals['_STOREDPAYMENTINSTRUMENTPROTO']._serialized_start=287
  _globals['_STOREDPAYMENTINSTRUMENTPROTO']._serialized_end=556
  _globals['_STOREDRELATEDAPPLICATIONPROTO']._serialized_start=558
  _globals['_STOREDRELATEDAPPLICATIONPROTO']._serialized_end=619
  _globals['_SUPPORTEDDELEGATIONSPROTO']._serialized_start=621
  _globals['_SUPPORTEDDELEGATIONSPROTO']._serialized_end=736
  _globals['_STOREDPAYMENTAPPPROTO']._serialized_start=739
  _globals['_STOREDPAYMENTAPPPROTO']._serialized_end=1023
# @@protoc_insertion_point(module_scope)
