# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: content/browser/content_index/content_index.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'content/browser/content_index/content_index.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1content/browser/content_index/content_index.proto\x12\rcontent.proto\"A\n\x15\x43ontentIconDefinition\x12\x0b\n\x03src\x18\x01 \x01(\t\x12\r\n\x05sizes\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\"\x9f\x01\n\x12\x43ontentDescription\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\x05\x12\x33\n\x05icons\x18\x05 \x03(\x0b\x32$.content.proto.ContentIconDefinition\x12\x12\n\nlaunch_url\x18\x06 \x01(\t\"\x91\x01\n\x0c\x43ontentEntry\x12\x36\n\x0b\x64\x65scription\x18\x01 \x01(\x0b\x32!.content.proto.ContentDescription\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x12\n\nlaunch_url\x18\x03 \x01(\t\x12\"\n\x14is_top_level_context\x18\x04 \x01(\x08:\x04true\"o\n\x0fSerializedIcons\x12<\n\x05icons\x18\x01 \x03(\x0b\x32-.content.proto.SerializedIcons.SerializedIcon\x1a\x1e\n\x0eSerializedIcon\x12\x0c\n\x04icon\x18\x01 \x01(\tB\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'content.browser.content_index.content_index_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_CONTENTICONDEFINITION']._serialized_start=68
  _globals['_CONTENTICONDEFINITION']._serialized_end=133
  _globals['_CONTENTDESCRIPTION']._serialized_start=136
  _globals['_CONTENTDESCRIPTION']._serialized_end=295
  _globals['_CONTENTENTRY']._serialized_start=298
  _globals['_CONTENTENTRY']._serialized_end=443
  _globals['_SERIALIZEDICONS']._serialized_start=445
  _globals['_SERIALIZEDICONS']._serialized_end=556
  _globals['_SERIALIZEDICONS_SERIALIZEDICON']._serialized_start=526
  _globals['_SERIALIZEDICONS_SERIALIZEDICON']._serialized_end=556
# @@protoc_insertion_point(module_scope)
